### ISSUE TITLE
Collector and Analyzer to check MS SQL connection and version.

### ISSUE THREAD

**Issue by chasehainey** [replicatedhq/troubleshoot#1005]
**Describe the rationale for the suggested feature.**

We have checks for other databases, we had a customer request similar functionality for MS SQL databases as well.

**Describe the feature**

- A collector will gather information from a MS SQL database, including connection status and version.
- An analyzer will make sure that if an external MS SQL database is attempting to be used, that there is a valid connection and a proper version being used.

```yaml
apiVersion: troubleshoot.sh/v1beta2
 kind: Preflight
 metadata:
   name: sample
 spec:
   collectors:
     - mssql:
         collectorName: mssql
         uri: sqlserver://username:password@hostname:1433/defaultdb
   analyzers:
     - mssql:
         checkName: Must be SQLServer 15.x or later
         collectorName: mssql
         outcomes:
           - fail:
               when: "connected == false"
               message: Cannot connect to SQLServer
           - fail:
               when: "version < 15.x"
               message: The SQLServer must be at least version 15
           - pass:
               message: The SQLServer connection checks out
```

**Describe alternatives you've considered**

**Additional context**

https://github.com/replicatedhq/troubleshoot/pull/990
