### ISSUE TITLE
Add support bundle spec used to collect a support bundle in the resulting bundle

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1027]
**Describe the rationale for the suggested feature.**

When we collect support bundles, we normally want to inspect the spec that was used to collect, redact and analyse the support bundle.

**Describe the feature**

Add the post-merge support bundle to the resulting bundle archive. This spec would need to be redacted off sensitive information. Redacting is a non-trivial task especially when a spec has an arbitrary script.

##### Considerations
- Collect more fields in the [execution summary](https://github.com/replicatedhq/troubleshoot/pull/935)
- Consider an approach where collectors redact their specs removing all sensitive information, and if not feasible, removing the fields entirely. Here is an example of a `run` collector spec. For collectors such as [redis](https://troubleshoot.sh/docs/collect/redis/) where the parameters are well defined, only the sensitive fields would be redacted.

_Defined spec_
```yaml
    - run:
        collectorName: "collect-sensitive"
        command: "sh"
        args:
          - -c
          - |
            USER="user" API_KEY="key" /opt/bank.corp/my-data-scraper > /tmp/all.txt
            grep "search-key"
```

_Redacted spec_
```yaml
    - run:
        collectorName: "collect-sensitive"
        command: "sh"
        args: ["***HIDDEN***"]
```
