### ISSUE TITLE
Ceph collector ignores user provided namespace

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#1041]
**Bug Description**

The Ceph collector ignores the user provided namespace from the [collector spec](https://troubleshoot.sh/docs/collect/ceph/#namespace-optional) and only uses the namespace from the kubeconfig context or `---namespace` flag. This is a regression caused by the struct refactor done last year in #670

**Expected Behavior**
The below should look for a rook-ceph installation in `some-namespace` and not `rook-ceph`.

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - ceph:
         namespace: some-namespace
```

**Steps To Reproduce**
Attempt to use the Ceph collector for a Ceph installation in a namespace other than `rook-ceph

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem
