### ISSUE TITLE
http collector timeouts

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1064]
**Describe the rationale for the suggested feature.**

If a http endpoint is not reachable, the collector would block until the collector times out which today is hard coded to `30s` places ([here](https://github.com/replicatedhq/troubleshoot/blob/main/pkg/preflight/run.go#L352) and [here](https://github.com/replicatedhq/troubleshoot/blob/main/cmd/collect/cli/run.go#L27)). As of today, the [http collector](https://troubleshoot.sh/docs/collect/http/) does not have any way to override this timeout leading to 

Here is a sample support bundle run summary

```
============ Collectors summary =============
Suceeded (S), eXcluded (X), Failed (F)
=============================================
http/rhealth-check (S) : 30,002ms
cluster-resources (S)                : 1,863ms
cluster-info (S)                     : 11ms

============ Redactors summary =============
In-cluster collectors : 456ms

============= Analyzers summary =============
Suceeded (S), eXcluded (X), Failed (F)
=============================================
No analyzers executed

Duration: 32,360ms
```

**Describe the feature**

Extend the collector to allow passing in a timeout

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - http:
        collectorName: healthz
        get:
          url: http://api:3000/healthz
          timeout: 5s
```

**Describe alternatives you've considered**

* Passing a CLI `--request-timeout` parameter
* Passing timeouts to [collector API options](https://github.com/replicatedhq/troubleshoot/blob/main/pkg/collect/collect.go#L29)in the library
