### ISSUE TITLE
Add flexibility to collectors & analysers to allow running external programs

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1078]
**Describe the rationale for the suggested feature.**

In an effort of supporting extensibility of using support-bundle & preflight binaries, it would be good to be able to run other available programs in a system without only relying on stdout/stderr/exit codes. Some example use cases that come to mind are

* Allowing cluster administrators that have home-built tools that collect and analyse data from hosts or k8s clusters to embed these tools without the need of rewriting them as specs to fit troubleshoot's current model.
* Allow embedding in automation pipelines e.g CI which come with a plethora of tools

**Describe the feature**

The "how" part is still open, but here is a suggestion that has been touched on in a community meeting (notes can be found [here](https://hackmd.io/yZbotEHdTg6TfRZBzb8Tcg)) and other various discussions.

* Extend the [run collector](https://troubleshoot.sh/docs/host-collect-analyze/run/)

Here is my fictional collector that collects audit event logs, enriches them with user data and stores the output in `$WORKSPACE_OUTPUT`. `$WORKSPACE_OUTPUT` is a unique directory created by the framework for this collector instance. Contents are them copied over to the bundle once executing the collector completes.

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: run
spec:
  hostCollectors:
    - run:
        collectorName: "enriched-audit-logs"
        command: "python3"
        args: ["--timeout", "10m", "--output-dir", "$WORKSPACE_OUTPUT"]
        # Arbitrary parameters which get stored in on disk as YAML/JSON and fed passed
        # on to the command via a $CONFIG env
        config:   # perhaps call it "params"?
          username: postgres
          password: <my-pass>
          dbHost: <hostname>
          map:
            key: value
          list:
            - val1
            - val2
```

* Create a similar analyser which takes in arbitrary parameters to operate on

**Open questions**
* How would this look like in-cluster? Extending the [run pod collector](https://troubleshoot.sh/docs/collect/run-pod/)?
* Is this the only way to allow extensibility?

**Inspirations**
* https://k9scli.io/topics/plugins/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable - GH action runners passes environment variables to jobs for them to store information that persists across jobs.
