### ISSUE TITLE
Preflight checks are returning many results instead of one 

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/troubleshoot#1089]
**Bug Description**

I would expected to have 1 success result when I am have a lot of them:

![Screenshot 2023-06-01 at 10 35 07](https://github.com/replicatedhq/troubleshoot/assets/7708031/848fb2f2-dd4d-4961-925f-d25cdec9f42b)

[kurl-builtin-oncluster-results-2023-03-31T17_42_31.txt](https://github.com/replicatedhq/troubleshoot/files/11124569/kurl-builtin-oncluster-results-2023-03-31T17_42_31.txt)

**Expected Behavior**

See only once : 

> Check PASS
> Title: Check for CNI 'not ready' messages
> Message: CNI is initialized

**Steps To Reproduce**

Run the following the spec with preflight in a k8s cluster:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: kurl-builtin-oncluster
spec:
  collectors:
    - run:
        collectorName: journalctl-kubelet
        image: busybox:1
        command: ["journalctl"]
        args: ["-u", "kubelet", "--no-pager", "-S", "7 days ago"]
  analyzers:
    - textAnalyze:
        checkName: "Check for CNI 'not ready' messages"
        file: run/journalctl-kubelet/journalctl-kubelet.logs
        ignoreIfNoFiles: true
        regex: "Container runtime network not ready.*cni plugin not initialized"
        outcomes:
          - pass:
              when: "false"
              message: "CNI is initialized"
          - fail:
              when: "true"
              message: "CNI plugin not initialized: there may be a problem with the CNI configuration on the host, check /etc/cni/net.d/*.conflist against a known good configuration"

```

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem

**Comment by xavpaice** [comment]
Probably need a bit more info here - the busybox image doesn't have journalctl so the pod doesn't actually start.

The same spec run as a support bundle doesn't produce any analyzer results at all, likely because the file doesn't exist in the bundle.  What we need to identify is what is causing the multiple results in preflight, when there's no actual result from the pod run.

For this particular check, I think what you're looking for is the host collector, rather than in-cluster collector, for the kubelet logs.

Would love to know if there's another reproducer we can see?

**Comment by xavpaice** [comment]
A very unhelpful reproducer (but a reproducer all the same):

Environment: Ubuntu 2204, kURL cluster, run preflight on the host itself.

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: kurl-builtin-oncluster
spec:
  collectors:
    - run:
        collectorName: journalctl-kubelet
        image: busybox:1
        command: ["echo"]
        args: ["Something"]
  analyzers:
    - textAnalyze:
        checkName: "Check for CNI 'not ready' messages"
        file: run/journalctl-kubelet/journalctl-kubelet.logs
        ignoreIfNoFiles: true
        regex: "Container runtime network not ready.*cni plugin not initialized"
        outcomes:
          - pass:
              when: "false"
              message: "CNI is initialized"
          - fail:
              when: "true"
              message: "CNI plugin not initialized: there may be a problem with the CNI configuration on the host, check /etc/cni/net.d/*.conflist against a known good configuration"
```
