### ISSUE TITLE
Outcomes title field ignored by analysers

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1093]
**Bug Description**

Analysis result outcomes have an [optional title field](https://troubleshoot.sh/docs/analyze/outcomes/#title) which can be used when multiple outcomes are defined, and when one would like to give specific outcomes more meaning by providing a more descriptive title.

**Steps To Reproduce**

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: kurl-builtin-oncluster
spec:
  collectors:
    - clusterResources: {}
    - clusterInfo: {}
  analyzers:
    - clusterPodStatuses:
        checkName: "Pod(s) health status(es)"
        outcomes:
          - fail:
              title: "Pod {{ .Name }} is unable to pull images"
              when: "== ImagePullBackOff"
              message: "A Pod, {{ .Name }}, is unable to pull its image. Status is: {{ .Status.Reason }}"
          - warn:
              title: "Pod {{ .Name }} is unhealthy"
              when: "!= Healthy"
              message: "A Pod, {{ .Name }}, is unhealthy with a status of: {{ .Status.Reason }}. Restarting the pod may fix the issue."
          - pass:
              title: "Pod {{ .Name }} is healthy"
              message: "Pod {{ .Name }} is healthy"
```

Collecting a support bundle using the spec above, where we have some failing pods, would render an analysis like below

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/681087/229490479-eb37b172-95a1-45de-8560-43b54519e684.png">

**Expected Behavior**

We expect to get results like below where each of the outcomes has a title with more context

<img width="1913" alt="Screenshot 2023-04-03 at 11 53 46" src="https://user-images.githubusercontent.com/681087/229490564-ee4e58d6-c788-45f5-9993-aff4e8ca2277.png">

**Additional Context**

* This struct that holds the title field is [here](https://github.com/replicatedhq/troubleshoot/blob/main/pkg/apis/troubleshoot/v1beta2/outcome.go#L3)
* Each analyser will need to be updated to consume the additional title field. At the moment each analyser by default uses the the anaylyser's [checkName](https://troubleshoot.sh/docs/analyze/#checkname) property as the title or a hard coded string. Take a look at the [pod status analyser](https://github.com/replicatedhq/troubleshoot/blob/main/pkg/analyze/cluster_pod_statuses.go#L143) for example

Include the following information.
- Troubleshoot version: Affect all versions of troubleshoot
