### ISSUE TITLE
blockDevices host preflight fails on older linux kernels

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/troubleshoot#1122]
**Bug Description**

https://github.com/replicatedhq/troubleshoot/pull/1063 introduced a change to collect PTTYPE from lsblk in the blockDevices collector. PTTYPE column is not supported on older Linux kernels (confirmed on older releases of RHEL 7 and 8). When running preflight, the check fails with the following error:

```
2023-04-17 16:16:55+00:00 [FAIL] Block Devices: Analyzer Failed: analyze: failed to get collected file: file host-collectors/system/block_devices.json was not collected
```

**Expected Behavior**

The blockDevices should be backwards compatible with all previously supported kernels.

**Steps To Reproduce**

Using image id centos-7-v20210512 on GCP with a block device attached if you run the following spec you will get the error with the v0.60.0 release of troubleshoot. This worked previous to the v0.60.0 release.

```
apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: kurl-builtin
spec:
  collectors:
  - blockDevices: {}

  analyzers:
  - blockDevices:
      includeUnmountedPartitions: true
      minimumAcceptableSize: 10737418240 # 1024 ^ 3 * 10, 10GiB
      outcomes:
      - pass:
          when: ".* == 1"
          message: One available block device
      - pass:
          when: ".* > 1"
          message: Multiple available block devices
      - fail:
          message: No available unformatted block devices were found
```

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
  v0.60.0
- Operating system
  RHEL variants
- Operating system version
  7 or 8
- Other details that might be helpful in diagnosing the problem
