### ISSUE TITLE
PostgreSQL collector ignoring sslmode parameter in the connection string

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1163]
**Bug Description**

When the [sslmode](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION) parameter is provided in the connection string, it indicates to the client what level of SSL verification should be done. `verify-full` for example verifies that the server certificate is signed using the CA cert provided and that the hostname making the connection matches the hostnames in the server cert (`Common Name` or `Subject Alternative Name`s). `verify-ca` on the other hand just checks that the server certificate is signed by the CA cert provided. There are other modes such as `disable` that tells the client to ignore any verification.

The collector below will fail to connect to the database if the server `hostname` is not in the server's certificate. This should not be the case since the connection string has `verify-ca` which should just verify that the certificate was signed by the CA.

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - postgres:
        collectorName: pg
        uri: postgresql://user:password@hostname:5432/defaultdb?sslmode=verify-ca
        tls:
          cacert: |
            -----BEGIN CERTIFICATE-----
            ...
            <truncated>
            ...
            -----END CERTIFICATE-----
```

**Expected Behavior**

The collector should respect the `sslmode` parameter provided in the connection string an collect a bundle containing `{"isConnected":true,"version":"X.X"}` in `<bundle>/postgres/pg.json`.

**Steps To Reproduce**

* Generate TLS parameters
```sh
CONFIG="
[req]
distinguished_name=dn
[ dn ]
[ ext ]
basicConstraints=CA:TRUE,pathlen:0
"

openssl genrsa -out ca.key 2048
openssl req -config <(echo "$CONFIG") -new -x509 -days 365 -key ca.key -subj "/CN=Root CA" -out ca.crt
openssl req -newkey rsa:2048 -nodes -keyout server.key -subj "/CN=server" -out server.csr
openssl x509 -req -extfile <(printf "subjectAltName=DNS:example.com,IP:127.0.0.1") -days 365 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt
chmod 600 server.key
```
* Start a postgres server exposing an SSL enabled port
```sh
docker run -d --rm --name postgres -p5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust -v "$(pwd)/server.crt:/var/lib/postgresql/server.crt:ro" -v "$(pwd)/server.key:/var/lib/postgresql/server.key:ro" -v "$(pwd)/ca.crt:/var/lib/postgresql/ca.crt:ro"  postgres:13-alpine -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key -c ssl_ca_file=/var/lib/postgresql/ca.crt
```
* Connect to the server using `psql`. This should succeed
```sh
psql -h localhost "sslmode=verify-ca sslrootcert=ca.crt hostaddr=127.0.0.1 port=5432 user=postgres"
```
* Collect a support bundle using the below spec. This will contain connection errors in `<bundle>/postgres/pg.json`
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - postgres:
        collectorName: pg
        uri: postgresql://postgres:postgres@localhost:5432/postgres?sslmode=verify-ca
        tls:
          cacert: |
            -----BEGIN CERTIFICATE-----
            <ca.crt>
            -----END CERTIFICATE-----

```
