### ISSUE TITLE
preflight has an unhelpful error message when there's no analyzers

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1173]
**Bug Description**

When I run a preflight check that has no analyzers in the spec, I get the error message that says "Error: no data has been collected", but that's not true.

**Expected Behavior**

I'd like to see an error message that says "Error: no analyzers specified"

**Steps To Reproduce**

Include the commands to reproduce the issue including any output. Any information that will help us to understand the problem is useful.  Feel free to paste long output into a [Github gist](https://gist.github.com) and include the link here.

Run a preflight check with the following spec:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: example
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources:
        ignoreRBAC: true
```

```
./preflight preflight.yaml
Error: no data has been collected
```

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem
