### ISSUE TITLE
support bundle with `--load-cluster-specs` does not merge multiple specs

### ISSUE THREAD

**Issue by cbodonnell** [replicatedhq/troubleshoot#1179]
**Bug Description**

Running `kubectl support-bundle --load-cluster-specs` does not merge the discovered specs and instead only runs the last spec discovered.

**Expected Behavior**

The command should merge all discovered specs and run the combined support bundle for the cluster.

**Steps To Reproduce**

1. Create a single ConfigMap with a support bundle spec that has collectors:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: support-bundle-spec-1
  labels:
    troubleshoot.io/kind: support-bundle
data:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: support-bundle-1
    spec:
      collectors:
      - clusterResources: {}
    status: {}
```

2. Run `kubectl support-bundle --load-cluster-specs`, it works as expected and runs the collector

3. Create another ConfigMap with a support bundle spec that does not have collectors:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: support-bundle-spec-2
  labels:
    troubleshoot.io/kind: support-bundle
data:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: support-bundle-2
    spec: {}
    status: {}
```

4. Run `kubectl support-bundle --load-cluster-specs`, it will return a message
```
Error: no collectors specified in support bundle
```

**Additional Context**

Include the following information.
- Troubleshoot version: v0.64.0
- Operating system:
- Operating system version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
- Other details that might be helpful in diagnosing the problem: The issue appears to be from [this spot](https://github.com/replicatedhq/troubleshoot/blob/v0.64.0/cmd/troubleshoot/cli/run.go#L364) in the code.  Each discovered bundle overwrites the last, so the last one is the only one that is returned.
