### ISSUE TITLE
Typo in PersistentVolumeClaim resource name in the `clusterResource` analyzer

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#1180]
**Bug Description**

In the `clusterResource` analyzer, when using `kind: PersistentVolumeClaim` it fails with:

```
Analyzer Failed

failed to find resource: failed to find resource
```

This is due to a typo in the resource names for the `clusterResource` analyzer here - https://github.com/replicatedhq/troubleshoot/blob/main/pkg/analyze/kube_resource.go#L25. The key name is incorrect which is what causes the issue. 

**Expected Behavior**

Using `kind: PersistentVolumeClaim` should not result in an error

**Steps To Reproduce**

```
    - clusterResource:
        checkName: Check PVC is RWX
        kind: PersistentVolumeClaim
        name: pvc-name
        namespace: some-namespace
        yamlPath: "spec.accessModes.[0]"
        expectedValue: ReadWriteMany
        outcomes:
          - fail:
              when: "false"
              message: The user provided PVC does not support ReadWriteMany (RWX) access mode.
          - pass:
              when: "true"
              message: The user provided PVC supports ReadWriteMany (RWX) access mode.
```

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with. 
v0.64.0

- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem
