### ISSUE TITLE
`clusterResource` analyzer ignores the `name` property and always uses the first object found

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#1184]
**Bug Description**

Today the analyzer will always return the first result object in the list because the `name` property being provided by the end-user is ignored. This is due to a collision in the variable name used for name of the object being searched for and the actual object in the collected contents.

See - https://github.com/replicatedhq/troubleshoot/blob/main/pkg/analyze/kube_resource.go#L96-L103

**Expected Behavior**

The analyzer should return the unique object expected and not the first result

**Steps To Reproduce**

Using:
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight
spec:
  collectors:
    - clusterResources: {}
  analyzers:
    - clusterResource:
        clusterScoped: false
        checkName: check-pvc
        kind: pvc 
        name: some-pvc
        namespace: default
        yamlPath: "spec.accessModes.[0]"
        expectedValue: ReadWriteOnce
        outcomes:
          - fail:
              when: "false"
              message: isFalse
          - pass:
              when: "true"
              message: isTrue
```

Even if `some-pvc` doesn't exist, as long as at least one PVC exists in the `default` namespace, and that PVC had an accessMode of `ReadWriteOnce` the analyzer would pass.
