### ISSUE TITLE
Ability to analyze properties of a PersistentVolumeClaim

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#1195]
**Describe the rationale for the suggested feature.**

Currently, Troubleshoot has no native way of analyzing a PersistentVolumeClaim to ensure that it has the minimum amount of storage required, or that it contains a required access or volume mode. A user may need this functionality in order to guarantee in a Preflight that a user provided PersistentVolumeClaim is in a desired configuration.

**Describe the feature**
Provide functionality where a user can check for a `min` or `max` value on  the storage size of a PVCZ as well as its access or volume modes.

Option 1: A separate analyzer similar to `nodeResources` - (https://github.com/replicatedhq/troubleshoot/blob/main/pkg/analyze/node_resources.go), provide a new analyzer where a user can check for a `min` or `max` value as well as access or volume modes.

```yaml
    - nodeResources:
        checkName: check-pvc-size
        outcomes:
          - pass:
              when: "storageCapacity > 100Gi"
              message: pass
          - fail:
              message: fail
    - nodeResources:
        checkName: check-access-mode
        outcomes:
          - pass:
              # Would also need to support a `contains` sort of operator for lists
              when: "accessMode == ReadWriteMany"
              message: pass
          - fail:
              message: fail
```

Option 2: Add functionality for parsing resource quantities to the existing `clusterResource `analyzer

https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#MustParse

```yaml
    - clusterResource:
        checkName: check-pvc-size
        kind: pvc
        name: pvc-name
        namespace: default
        yamlPath: "spec.resources.requests.storage"
        regexGroups: '(?P<PVCSize>\d+[A-Za-z]{2})'
        outcomes:
          - pass:
              when: "PVCSize > 100Gi"
              message: PVC is the right size
          - fail:
              message: PVC is too small
    - clusterResource:
        checkName: check-access-mode
        kind: pvc
        name: pvc-name
        namespace: default
        yamlPath: "spec.accessModes"
        regex: ReadWriteMany
        outcomes:
            - fail:
                when: "false"
                message: is not RWX
            - pass:
                when: "true"
                message: is RWX
```
