### ISSUE TITLE
Ability to compare entire files in a preflight

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1228]
**Describe the rationale for the suggested feature.**

Some use cases require comparing two collected files together. An example use case is when checking whether an upcoming release has had any changes introduced to a configuration file check the differences.

**Describe the feature**

TBD

**Describe alternatives you've considered**

**Additional context**

**Comment by vsklevko** [comment]
I would love to add context with an example here. I have two collectors that collect information from KOTS CLI to determine if there're any differences in the configuration between the version deployed and version to be installed. This is done in Preflight:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
    name: apisix-preflight-checks
spec:
    collectors:
        - exec:
              name: upcoming-config
              collectorName: check-upcoming-config
              selector:
                  - app=kotsadm
                  - kots.io/kotsadm=true
              containerName: kotsadm
              command: ["./kots"]
              args:
                  [
                      "get",
                      "config",
                      '--appslug={{repl LicenseFieldValue "appSlug" }}',
                      "--sequence=-1",
                      "-n",
                      "{{repl Namespace}}",
                  ]
        - exec:
              name: current-config
              collectorName: check-current-config
              selector:
                  - app=kotsadm
                  - kots.io/kotsadm=true
              containerName: kotsadm
              command: ["./kots"]
              args:
                  [
                      "get",
                      "config",
                      '--appslug={{repl LicenseFieldValue "appSlug" }}',
                      "--sequence={{repl Sequence }}",
                      "-n",
                      "{{repl Namespace}}",
                  ]
```

Both files produce an output with contents of YAML output:

```yaml
apiVersion: kots.io/v1beta1
kind: ConfigValues
metadata:
  creationTimestamp: null
     spec:
       values:
            dashboard-replica-count:
              default: "1"
            gateway-replica-count:
              default: "1"
status: {}
```

Inside the analyzer however there's no way to compare the output of both as well as YAML analyzer can compare to a static content at the moment, so It'd be nice to have something like:

```yaml
- fileCompare:
              checkName: Compare YAML Example
              collectorName: check-upcoming-config
              collectorCompareToName: check-actual-confing
```
