### ISSUE TITLE
Ability to specify path Wildcard in CompareYAML analyser

### ISSUE THREAD

**Issue by vsklevko** [replicatedhq/troubleshoot#1229]
**Describe the rationale for the suggested feature.**

In the preflight checks it's sometimes possible that a collector collects an information from multiple nodes and stores them within specific filenames that are not known beforehand and therefore makes it impossible to check the output agains the path.

**Describe the feature**

The feature should allow wildcards in the `fileName` so that all the files that match such a wildcard are checked agains the condition.

**Describe alternatives you've considered**

n/a

**Additional context**

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
    name: apisix-preflight-checks
spec:
    collectors:
        - exec:
              name: upcoming-config
              collectorName: check-upcoming-config
              selector:
                  - app=kotsadm
                  - kots.io/kotsadm=true
              containerName: kotsadm
              command: ["./kots"]
              args:
                  [
                      "get",
                      "config",
                      '--appslug={{repl LicenseFieldValue "appSlug" }}',
                      "--sequence=-1",
                      "-n",
                      "{{repl Namespace}}",
     analyzers:
         - yamlCompare:
              checkName: Compare YAML Example
              fileName: '[a-z]*-config/arthur/kotsadm-[a-z0-9-]*/[a-z0-9-]*-stdout.txt'
              path: "spec.values.some_value_to_check.value"
              value: "0"
              outcomes:
                  - fail:
                        when: "false"
                        message: The collected data does not match the value.
                  - pass:
                        when: "true"
                        message: The collected data matches the value.
```

In the example above we'd collect the outputs of the command reading the STDOUT of those commands and check that the value of those evaluations are the same.
