### ISSUE TITLE
Add redactors to SupporBundle & Preflight specs

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1230]
**Describe the rationale for the suggested feature.**

We currently have a separate [`Redactors`](https://github.com/replicatedhq/troubleshoot/blob/557a1381a952d51d6f5fcc363ea169d45478da4b/pkg/apis/troubleshoot/v1beta2/redact_types.go#L37) spec for defining redactors. This means that for every `SupportBundle` or `Preflight` that requires redactors defined, a separate manifest with required redactors would need to be specified and passed on to the tools consuming these manifests (`support-bundle`, `preflight` binaries etc). This creates a bit of confusion when crafting specs. 

People would expect to define a spec like below
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: support-bundle-name
spec:
  collectors:
    - mycollector
  analyzers:
    - myanalyzer
  redactors:
    - myredactor
```

Instead they need two specs i.e
_support bundle_
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: support-bundle-name
spec:
  collectors:
    - mycollector
  analyzers:
    - myanalyzer
```

_redactors_
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Redactor
metadata:
  name: redactors
spec:
  redactors:
    - myredactor
```

**Describe the feature**

Add the [`RedactorSpec`](https://github.com/replicatedhq/troubleshoot/blob/557a1381a952d51d6f5fcc363ea169d45478da4b/pkg/apis/troubleshoot/v1beta2/redact_types.go#L24) to [`SupportBundleSpec`](https://github.com/replicatedhq/troubleshoot/blob/557a1381a952d51d6f5fcc363ea169d45478da4b/pkg/apis/troubleshoot/v1beta2/supportbundle_types.go#L24), [`PreflightSpec`](https://github.com/replicatedhq/troubleshoot/blob/557a1381a952d51d6f5fcc363ea169d45478da4b/pkg/apis/troubleshoot/v1beta2/preflight_types.go#L24) and [`HostPreflightSpec`](https://github.com/replicatedhq/troubleshoot/blob/557a1381a952d51d6f5fcc363ea169d45478da4b/pkg/apis/troubleshoot/v1beta2/hostpreflight_types.go#L24)

**Describe alternatives you've considered**

Leave things as they are

**Additional context**

Having fewer high level troubleshoot kinds makes it easier to craft specs. Eventually, it would be good to deprecate `Redactors` spec.
