### ISSUE TITLE
Preflight truncates the message if it is long

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1237]
**Bug Description**

When reviewing the results of a preflight, the 'message' is truncated by wrapping if the screen is certain widths.

e.g. the message field:

```
              message: |-
                Harbor runs best with a minimum of 8 GB of memory. Your current cluster has less
                than 8 GB of memory available to run workloads. For the best experience, consider
                increasing cluster capacity or installing into a different cluster.
```

When I run preflight interactively, I get different results based on the screen size:

![Screenshot 2023-06-22 at 4 48 29 PM](https://github.com/replicatedhq/troubleshoot/assets/5035609/38dad247-4595-41fe-91b7-fd66665376c3)

![Screenshot 2023-06-22 at 4 51 51 PM](https://github.com/replicatedhq/troubleshoot/assets/5035609/340ff08b-9169-4d0f-b532-05857f1985d5)

![Screenshot 2023-06-22 at 4 51 30 PM](https://github.com/replicatedhq/troubleshoot/assets/5035609/0b3c1180-e87d-4baa-a96d-332645bf39d2)

![Screenshot 2023-06-22 at 4 51 08 PM](https://github.com/replicatedhq/troubleshoot/assets/5035609/64662a48-eecb-43e0-99ba-e96c91f09d16)

![Screenshot 2023-06-22 at 4 50 39 PM](https://github.com/replicatedhq/troubleshoot/assets/5035609/ef2f49e9-6d85-4681-a35f-3b995c67ea8e)

**Expected Behavior**

All the text, and the URL, should be displayed, and they should be wrapped according to the screen size.

**Steps To Reproduce**

Make a preflight with the following spec:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: harbor-preflight-checks
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.19.x"
              message: |-
                Your Kubernets cluster is running a version of Kubernetes that is not supported by the Harbor container
                registry and your installation will not succeed. Please upgrade your cluster or install to a different
                cluster running at least Kubernetes 1.19, ideally version 1.24.0 or later.
              uri: https://github.com/bitnami/charts/blob/main/bitnami/harbor/README.md
          - warn:
              when: "< 1.24.0"
              message: |-
                Your Kubernetes cluster is running a version of Kubernetes that is not longer supported by the Kubernetes
                community. If you are receiving extended support from your Kubernetes provider you may be able to ignore
                this warning. If not, we recomend that you upgrade your cluster to at least version 1.24.0.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster is running a version of Kubernetes that is supported by the Harbor container registry.
    - nodeResources:
        checkName: Cluster CPU resources are sufficient to install and run Harbor
        outcomes:
          - fail:
              when: "sum(cpuAllocatable) < 2"
              message: |-
                Harbor requires a minimum of 2 CPU cores in order to run, and runs best with
                at least 4 cores. Your current cluster has less than 2 CPU cores available to Kubernetes
                workloads. Please increase cluster capacity or install into a different cluster.
              uri: https://goharbor.io/docs/2.8.0/install-config/installation-prereqs/
          - warn:
              when: "sum(cpuAllocatable) < 4"
              message: |-
                Harbor runs best with a minimum of 4 CPU cores. Your current cluster has less
                than 4 CPU cores available to run workloads. For the best experience, consider
                increasing cluster capacity or installing into a different cluster.
              uri: https://goharbor.io/docs/2.8.0/install-config/installation-prereqs/
          - pass:
              message: Your cluster has sufficient CPU resources available to run Harbor
    - nodeResources:
        checkName: Cluster memory is sufficient to install and run Harbor
        outcomes:
          - fail:
              when: "sum(memoryAllocatable) < 4G"
              message: |-
                Harbor requires a minimum of 4 GB of memory in order to run, and runs best with
                at least 8 GB. Your current cluster has less than 4 GB available to Kubernetes
                workloads. Please increase cluster capacity or install into a different cluster.
              uri: https://goharbor.io/docs/2.8.0/install-config/installation-prereqs/
          - warn:
              when: "sum(memoryAllocatable) < 8Gi"
              message: |-
                Harbor runs best with a minimum of 8 GB of memory. Your current cluster has less
                than 8 GB of memory available to run workloads. For the best experience, consider
                increasing cluster capacity or installing into a different cluster.
              uri: https://goharbor.io/docs/2.8.0/install-config/installation-prereqs/
          - pass:
              message: Your cluster has sufficient memory available to run Harbor
```

Save it as 'preflight.yaml'

run `kubectl preflight preflight.yaml`

Change the size of your terminal window to show different outputs.

**Additional Context**
