### ISSUE TITLE
Create a regular expression host analyser

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1263]
**Describe the rationale for the suggested feature.**

It allow using regular expressions to search for text from files collected by host collectors, we need to create an `HostAnalyzer` similar to https://troubleshoot.sh/docs/analyze/regex/. This would allow us to be able to have a spec like below

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example
spec:
  hostCollectors:
    - run:
        collectorName: "localhost-ips"
        command: "sh"
        args: ["-c", "host localhost"]
  hostAnalyzers:
    - textAnalyze:
        checkName: Check if localhost resolves to 127.0.0.1
        fileName: host-collectors/run-host/localhost-ips.txt
        regex: 'localhost has address 127.0.0.1'
        outcomes:
          - fail:
              when: "false"
              message: "'localhost' does not resolve to 127.0.0.1 ip address"
          - pass:
              when: "true"
              message: "'localhost' resolves to 127.0.0.1 ip address"
```

**Describe the feature**

Create a new `HostAnaylzer` that reuses https://github.com/replicatedhq/troubleshoot/blob/main/pkg/analyze/text_analyze.go code. Ensure the code remains DRY.

**Additional information**
This will allow us to resolve https://github.com/replicatedhq/troubleshoot-specs/issues/56 issue
