### ISSUE TITLE
Mssql analyser not working as intended

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1289]
**Bug Description**

When running the preflight binary, the `mssql` analyser is not analysing data collected data

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - mssql:
        collectorName: mssql
        uri: sqlserver://username:password@hostname:1433/defaultdb
  analyzers:
    - mssql:
        checkName: Must be SQLServer 15.x or later
        collectorName: mssql
        outcomes:
          - fail:
              when: "connected == false"
              message: Cannot connect to SQLServer
          - fail:
              when: "version < 15.x"
              message: The SQLServer must be at least version 15
          - pass:
              message: The SQLServer connection checks out
```

<img width="1092" alt="image" src="https://github.com/replicatedhq/troubleshoot/assets/681087/33f3a9bb-c93a-4ece-b1aa-0f4744c3d5bc">

**Expected Behavior**

The analyser should fail with `Cannot connect to SQLServer` message

Include a description of the expected behaviour here.

**Steps To Reproduce**

Run `preflight spec.yaml` where the spec contains the yaml above

Include the following information.
- Troubleshoot version: `v0.70.2`
