### ISSUE TITLE
Add a timeout to the run host collector

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1377]
**Describe the rationale for the suggested feature.**

The [run host collector](https://troubleshoot.sh/docs/host-collect-analyze/run/) us used to run arbitrary command/programs which the collector has little control of with regards to how long the process takes. This can lead to the collector running for too long and in some cases, not even stopping

Collecting a support bundle using the spec below will never stop

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: run
spec:
  hostCollectors:
    - run:
        name: "ping-google"
        command: "ping"
        args:
          - "google.com"
```

**Describe the feature**

Add a `timeout` field that can be used to limit how long the collector should run. The timeout should be
- A `string` [parsable into a time.Duration](https://pkg.go.dev/time#ParseDuration)
- Non negative. If its a negative value, default to passing no timeout

Here is an example spec

```yaml
    - run:
        name: "ping-google"
        timeout: 
        command: "ping"
        args:
          - "google.com"
```

**Describe alternatives you've considered**

Leave things as they are 

**Additional context**

- The run pod collector has a [timeout field](https://troubleshoot.sh/docs/collect/run-pod/#timeout-optional) which behaves as described above. This can be "borrowed"
- Eventually, [exec.CommandContext](https://pkg.go.dev/os/exec#CommandContext) would end up being called if there is a timeout
