### ISSUE TITLE
Misbehaviour when merging a support bundle spec with an empty or missing collectors list

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1417]
**Bug Description**

Passing in a support bundle spec that does not have collectors ought to add the `clusterInfo` and `clusterResources` collectors by default. This is not happening at the moment.

```sh
cat <<EOF | support-bundle --dry-run -
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: simplest-support-bundle
spec:
  collectors: []
EOF
``` 

Running the command above results in the output below

```sh
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  creationTimestamp: null
  name: merged-support-bundle-spec
spec: {}
status: {}
```

Trying to collect a support bundle with the same spec ends up failing like so

```sh
$ cat <<EOF | support-bundle -
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: simplest-support-bundle
spec:
  collectors: []
EOF

Error: failed to run collect and analyze process: failed to generate support bundle
✘-1 ~/repos/replicated/troubleshoot [main {origin/main}|…7⚑ 9]
```

**Expected Behaviour**

The expected output out of the dry run command above should be
```sh
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  creationTimestamp: null
  name: merged-support-bundle-spec
spec:
  collectors:
  - clusterInfo: {}
  - clusterResources: {}
status: {}
```

Include a description of the expected behaviour here.

**Additional Context**

This regression is related to https://github.com/replicatedhq/troubleshoot/issues/1393

Include the following information.
- Troubleshoot version - `v0.79.0`
- Operating system - Darwin

**Comment by chris-sanders** [comment]
@banjoh it's not clear to me that this is a bug.

Are you suggesting that a user _can not override the built in collectors_ even if they intend to? Passing an empty collector 
seems like an intentional disabling of the collectors.

**Comment by banjoh** [comment]
> Are you suggesting that a user _can not override the built in collectors_ even if they intend to? Passing an empty collector seems like an intentional disabling of the collectors.

We give users the ability to [exclude](https://troubleshoot.sh/docs/collect/collectors/#exclude) collectors where they can have a spec like below

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: exluded-collectors
spec:
  collectors:
  - clusterInfo:
      exclude: true
  - clusterResources:
      exclude: true
```

As for the regression, the behaviour that troubleshoot has had was to add default collectors whenever `collectors` are not defined i.e field missing entirely in the spec, or if an empty list is defined (`collectors: []`). This behaviour is implied [here](https://troubleshoot.sh/docs/support-bundle/collecting/#collect-a-support-bundle). Also, both [clusterResources](https://troubleshoot.sh/docs/collect/cluster-resources/) and [clusterInfo](https://troubleshoot.sh/docs/collect/cluster-info/) have been documented as collectors that will be added to the spec if they are missing

> This collector is a default collector and it will be automatically included in your collector spec if you don't include it. This collector cannot be removed.

An old [bug](https://github.com/replicatedhq/troubleshoot/issues/170) was reported questioning why the default collectors are added, and the conclusion was that this was an intended change

According to the implementation that was there before, the behaviour should be

- Default specs added if `collectors` is empty list
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: spec
spec:
  collectors: []
```

- Default specs added if `collectors` is missing
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: spec
spec:
  analyzers: []
```

- Default specs added if `collectors` exists but default collectors not present
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: spec
spec:
  collectors:
  - logs: {}
```

- `support-bundle` should error
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: spec
spec: {}
```

**Comment by banjoh** [comment]
I suggest considering adding default collectors to a spec that has `spec: {}`

**Comment by chris-sanders** [comment]
@banjoh I agree with your suggestion about `spec: {}`

What do you think about:

This will remove default collectors, an if it's the only spec error accordingly.

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: spec
spec:
  collectors: []
```

This works the same as `spec: {}` and the same as if you set no collectors at all with `analyzers: {}`

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: spec
spec:
  collectors: {}
```

No change to the disable fields. They keep working as they are now.

**Comment by banjoh** [comment]
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: spec
spec:
  collectors: {}
```

This would be an invalid spec. `collectors`, `analyzers` and `redactors` are all lists, not objects (key/value pairs). Today this is ignored and will be treated as if no spec was provided i.e the entire spec will be dropped.

As for removing default collectors with `collectors: []`, I'm yet to see how this will be utilised in practice. If such a spec is the only one, `support-bundle` and `preflight` will just error. If the spec gets merged with another, the default collectors get added anyway. At what point will users need to define `collectors: []`?

**Comment by chris-sanders** [comment]
Oh I see what you're saying, so does `collectors: []` need to be a required input? That seems strange.

**Comment by banjoh** [comment]
> Oh I see what you're saying, so does `collectors: []` need to be a required input? That seems strange.

`collectors` is not a required field.

**Comment by chris-sanders** [comment]
Ok so make `spec: {}` valid, empty values on `collectors, analyzers` are going to be valid and include the defaults because you could simply not specify anything. That makes since to me +1

**Comment by banjoh** [comment]
When we **ONLY** have host collectors, we do not add default in-cluster collectors, naturally. This means the spec below will also **not** add the default collectors

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
spec:
  hostCollectors:
  - cpu: {}
  collectors: []
```

A user has to add at least one in-cluster collector (even one of the default ones) to get default collectors in like below

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
spec:
  hostCollectors:
  - cpu: {}
  collectors:
  - logs: {}
```

I'm happy with this approach, but posting here solicit feedback.

ping @chris-sanders
