### ISSUE TITLE
Is there a better way to give hints about parse/format errors?

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/troubleshoot#1436]
**Describe the rationale for the suggested feature.**

Right now, simple YAML errors like missing an indent result in `nonexistent analyzer` errors.

<img width="549" alt="Screenshot 2024-01-28 at 6 25 37 PM" src="https://github.com/replicatedhq/troubleshoot/assets/3730605/dcb9ed32-9f50-4de8-b5ec-c23072aacc6f">

**Describe the feature**

I picked up some code and ran support-bundle, only to find that It output `nonexistent analyzer`

The code in the file is

```yaml
        - distribution:
          outcomes:
            - pass:
                when: "== kurl"
                message: kurl is a supported platform
            - pass:
                when: "== gke"
                message: GKE is a supported platform
```

but should be

```yaml
        - distribution:
            outcomes:
              - pass:
                  when: "== kurl"
                  message: kurl is a supported platform
              - pass:
                  when: "== gke"
                  message: GKE is a supported platform
```

**Proposal: Detect likely format errors** To whatever extent we can, which may be "not much", try to hint that this may be a yaml/parse error when the body of an analyzer evaluates to `null`.

A proposed error message might look like

> Could not parse an analyzer at index $N. Please ensure the object key is a valid analyzer type and parameters are indented as children of the analyzer type name. See $DOCS_LINK for more information.

<img width="1596" alt="Screenshot 2024-01-28 at 6 21 22 PM" src="https://github.com/replicatedhq/troubleshoot/assets/3730605/867284d5-be8a-4ac8-879a-6f2fb92b8038">

**Proposal: Strict format requirements** it seems like the YAML parser that consumes the list element evaluates to `distribution = nil` and then just drops the `outcomes` block on the floor since it can't be unmarshalled onto any known struct field of type [Analyze](https://github.com/replicatedhq/troubleshoot/blob/1447e18c5686104d990a3189f36107a556630eb5/pkg/apis/troubleshoot/v1beta2/analyzer_shared.go#L235). Y'all could consider failing or warning whenever unrecognized fields are provided, but this has some backwards-compatibility issues and probably needs some kind of `strict-parsing` opt-in. For example in the actual failed analyzer UI, could show something like

> Parse error at index $N (or line: $N) -- one or more unknown object fields will be ignored: [`outcomes`].

**Describe alternatives you've considered**

I suppose I could make fewer yaml mistakes 😅 

**Additional context**
