### ISSUE TITLE
clusterVersion analyzer does not detect 1.29 correctly in EKS

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1441]
**Bug Description**

A report arrived stating that when the query `when: "< 1.29.0"` is used in the `outcomes` section of the `clusterVersion` analyzer, a cluster running 1.29 on EKS does not report correctly (i.e. it reports true for this condition).

**Expected Behavior**

EKS running k8s 1.29 should evaluate false for `when: "< 1.29.0"`

**Steps To Reproduce**

Create an EKS cluster with k8s 1.29
use the following preflight spec:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: kubernetes-version
spec:
  collectors: []
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: < 1.24.0
              message: >-
                The application requires at Kubernetes 1.24.0 or later, and
                recommends 1.29.0.
              uri: 'https://kubernetes.io'
          - warn:
              when: < 1.29.0
              message: >-
                Your cluster meets the minimum version of Kubernetes, but we
                recommend you update to 1.29.0 or later.
              uri: 'https://kubernetes.io'
          - pass:
              message: >-
                Your cluster meets the recommended and required versions of
                Kubernetes.
```

The output should be 'pass', but is 'warn'.

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem

Edited: corrected EBS -> EKS @adamancini

**Comment by gilvan-fernandes** [comment]
Notice that it is EKS, not EBS.
And, the problem happens on SupportBundle and Prefligh.

The additional information is on the support-bundle:

{
  "info": {
    "major": "1",
    "minor": "29+",
    "gitVersion": "v1.29.0-eks-c417bb3",
    "gitCommit": "787475c0c70a6bc04f58927faf4d30969314cf59",
    "gitTreeState": "clean",
    "buildDate": "2023-12-13T19:28:31Z",
    "goVersion": "go1.21.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "string": "v1.29.0-eks-c417bb3"
}

kind: SupportBundle
spec:
  versionNumber: v0.76.4-0.20231102041618-a7bb9ea31e61

**Comment by xavpaice** [comment]
From my test EKS 1.29:

```yaml
{
  "info": {
    "major": "1",
    "minor": "29+",
    "gitVersion": "v1.29.0-eks-c417bb3",
    "gitCommit": "787475c0c70a6bc04f58927faf4d30969314cf59",
    "gitTreeState": "clean",
    "buildDate": "2023-12-13T19:28:31Z",
    "goVersion": "go1.21.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "string": "v1.29.0-eks-c417bb3"
}
```

From a k3s test cluster at 1.29:

```yaml
{
  "info": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.0+k3s1",
    "gitCommit": "3190a5faa28d7a0d428c756d67adcab7eb11e6a5",
    "gitTreeState": "clean",
    "buildDate": "2023-12-22T00:03:57Z",
    "goVersion": "go1.21.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "string": "v1.29.0+k3s1"
}
```

I suspect the issue is with the minor having an extra `+`.
