### ISSUE TITLE
Daemonset collector

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1446]
**Describe the rationale for the suggested feature.**

I can currently use the `runPod` collector to run a pod with some basic commands.  I use this to check connectivity from the cluster to the outside world, for example, using `wget` as a basic test.

In a multi-node cluster, I want to ensure that every node meets this criteria - i.e. in this case, all the nodes can connect and download from a URL I specified.  There's many other examples where I might want to run the same thing on all the nodes.

**Describe the feature**

Duplicate the `runPod` collector to run a daemonset, and collect all the results to files for analysis later.

**Describe alternatives you've considered**

n/a

**Additional context**

This came up when using `preflight` to confirm connectivity tests within Compatibility Matrix.  For multi-node clusters, I want to be sure that the nodes are all successful.  Current spec:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: connectivity
spec:
  collectors:
    - runPod:
        name: connectivity
        namespace: default
        podSpec:
          containers:
            - name: wget
              image: busybox:1
              command: ["wget"]
              args: ["-O", "-", "https://docs.replicated.com"]

  analyzers:
    - textAnalyze:
        checkName: "connectivity"
        fileName: connectivity/connectivity.log
        regex: 'title=\"Replicated Docs\"'
        outcomes:
          - pass:
              when: "true"
              message: Successful download from from https://docs.replicated.com
          - fail:
              message: Was unable to download from https://docs.replicated.com
```

Ideally, that would be a DaemonSet that I can use with a better regex to confirm that all the nodes have connectivity rather than just the one that the pod landed on.
