### ISSUE TITLE
Ability to skip cluster-resources collector

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1447]
**Describe the rationale for the suggested feature.**

When I run a very simple and compact preflight, which has analyzers only for the things in the collectors I have specified, I do not need to use the info collected by `cluster-resources`.  This collector takes time to run and therefore slows down everything that is waiting for the preflight result.

Currently cluster-info and cluster-resources are added automatically if there are other collectors specified, regardless if they're used.  This is handy for support-bundles, but in `preflight` this information is thrown away so the collection time is a waste.

**Describe the feature**

Add a boolean switch for the CLI `--add-default-collectors`, default true, that controls if the default collectors are added to a spec if none are specified.

**Describe alternatives you've considered**

Stop adding the defaults with preflight:
* would likely cause backward compatibility issues since folks expect it to be there

**Additional context**

Example where cluster-resources is not needed or used:
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: connectivity
spec:
  collectors:
    - runPod:
        name: connectivity
        namespace: default
        podSpec:
          containers:
            - name: wget
              image: busybox:1
              command: ["wget"]
              args: ["-O", "-", "https://docs.replicated.com"]

  analyzers:
    - textAnalyze:
        checkName: "connectivity"
        fileName: connectivity/connectivity.log
        regex: 'title=\"Replicated Docs\"'
        outcomes:
          - pass:
              when: "true"
              message: Successful download from from https://docs.replicated.com
          - fail:
              message: Was unable to download from https://docs.replicated.com
```

**Comment by banjoh** [comment]
At the moment, the way to remove the default collectors is to explicitly add them, and disable them like this

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
spec:
  collectors:
    - clusterResources:
        exclude: true
    - clusterInfo:
        exclude: true
```

Would this be sufficient?


```sh
preflight spec.yaml --debug --interactive=false
I0205 10:46:45.705316   27849 collect.go:239] excluding "cluster-resources" collector
I0205 10:46:45.705338   27849 collect.go:239] excluding "cluster-info" collector
name: run-pod              status: running         completed: 2    total: 3
name: run-pod              status: completed       completed: 3    total: 3

   --- PASS connectivity
      --- Successful download from from https://docs.replicated.com
--- PASS   connectivity
PASS

============ Collectors summary =============
Succeeded (S), eXcluded (X), Failed (F)
=============================================
run-pod (S)           : 3,110ms
cluster-resources (X) : 0ms
cluster-info (X)      : 0ms

============ Redactors summary =============
No redactors executed

============= Analyzers summary =============
Succeeded (S), eXcluded (X), Failed (F)
=============================================
connectivity (S) : 0ms

Duration: 3,125m
```

**Comment by xavpaice** [comment]
perfect!

**Comment by koolay** [comment]
It is not work as expected.
It will still to collect the log resource.
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - clusterResources: 
        exclude: true
    - clusterInfo:
        exclude: true
    - logs:
        selector:
          - app.kubernetes.io/name=redis
        namespace: redis-system
        # name: logs
        # containerNames:
        #   - api
        #   - node
        limits:
          maxAge: 720h
          maxLines: 1000
          maxBytes: 5000000

```

![image](https://github.com/replicatedhq/troubleshoot/assets/4273490/ab534fe0-0a48-4041-9957-92e25aaa0daf)
