### ISSUE TITLE
Host analysers are not deduplicating during multiple spec merges

### ISSUE THREAD

**Issue by ricardomaraschini** [replicatedhq/troubleshoot#1485]
**Bug Description**

If I have the same host analyser defined in two different specs they end up showing twice when I run `kubectl support-bundle spec0 spec1`. The same does not happen with a regular analyser, only with host analysers. It seems like the same deduplication applied for analysers is not applied for host analysers.

**Expected Behavior**

My duplicated host analyser to show up only once.

**Steps To Reproduce**

Create two specs with the same host analyser:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: embedded-cluster-host-support-bundle
spec:
  hostCollectors:
  - memory: {}
  hostAnalyzers:
  - memory:
      checkName: Amount of Memory
      outcomes:
      - warn:
          when: "< 2G"
          message: At least 2G of memory is recommended
      - pass:
          message: The system has at least 2G of memory
```

Then run the support-bundle passing both specs:

```
kubectl support-bundle spec0.yaml spec1.yaml
```

With the `--dry-run` flag I can see that the same host analyser is duplicated in the merged result.
