### ISSUE TITLE
Collecting a support bundle using troubleshoot.replicated.com/v1beta1 fails

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1502]
**Bug Description**

Parsing `troubleshoot.replicated.com/v1beta1` specs in troubleshoot fails when collecting support bundles.

spec.yaml
```
kind: Collector
apiVersion: troubleshoot.replicated.com/v1beta1
spec:
  collectors:
  - clusterInfo: {}
```

**Expected Behavior**

`troubleshoot.replicated.com/v1beta1` specs should be converted to `troubleshoot.sh/v1beta2` and correctly parsed. Collecting a support bundle should succeed with the collectors defined having run.
