### ISSUE TITLE
Troubleshoot logs collector requires a label value 

### ISSUE THREAD

**Issue by bagel-dawg** [replicatedhq/troubleshoot#1518]
**Bug Description**

The following support bundle spec returns no logs for a variety of pods that each have an `app` label with different values.

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: support-bundle
spec:
  collectors:
  - logs:
      collectorName: pod-logs
      selector:
      - app
      name: logs
      limits:
        maxAge: 24h
```

**Expected Behavior**

The support bundle generated should include any pod that has the label `app`.

**Steps To Reproduce**

Create a support bundle with the above spec and run the following command against a cluster with pods with an `app` label with any value:
```
support-bundle .github/build/support-bundle.yaml \
  --interactive=false \
  --output=artifacts/support-bundle.tar.gz \
  --request-timeout=5m
```

**Additional Context**

Additionally, `sbctl` should be able to interact with these logs in the same way that they can with the current implementation. I often use sbctl in CICD as a debugging tool and it can be painful to keep up with multiple services.
