### ISSUE TITLE
Should NodeResources analyzer allow filtering by Label?

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/troubleshoot#159]
Right now, NodeResources allows filtering by resources, but not by label:

https://github.com/replicatedhq/troubleshoot/blob/d9625477d2a552f7b5dc1289449527704fea1a95/pkg/apis/troubleshoot/v1beta1/analyzer_shared.go#L81-L96

### Use Case

I want to be able to require a certain number of nodes with certain labels as a preflight check, e.g. to run the Mongo Operator, the implementation today uses node labels as a scheduling requirement. 

https://github.com/jasonmimick/mongodb-k8s/blob/master/templates/ops-manager.yaml#L20-L27

Furthermore, the requirements I present for memory and CPU should only be applied to the nodes that are schedulable for my application, so filters seems like the right place to add this (rather than, say, a separate analyzer spec)

### Examples

Option 1, `matchLabels`

```yaml
    - nodeResources:
        checkName: Must have 1 node with 16 GB (available) memory and 5 cores (on a single node) with label kubernets.io/role=database-primary-replica
        filters:
          allocatableMemory: 16Gi
          cpuCapacity: "5"
          selector:
            matchLabels: 
               kubernetes.io/role=database-primary-replica
        outcomes:
          - fail:
              when: "count() < 1"
              message: Must have 1 node with 16 GB (available) memory and 5 cores (on a single node) with label kubernets.io/role=database-primary-replica
          - pass:
              message: This cluster has a node with enough memory.
```

Option 2, use the exact syntax for nodeSelectors from pod spec

```yaml
          - matchExpressions:
            - key: kubernetes.io/role 
              operator: In
              values:
              - database-primary-replica 
```

**Comment by matias-manavella-nimble** [comment]
@marccampbell @dexhorthy Hi guys, I am working on the final details of this feature, I followed option 1 of dex's suggestion, but I used a dictionary instead of a string value, like this. If you think it's ok, I send the PR tomorrow morning

```yaml
filters:
  cpuCapacity: "6"
  selector: 
     matchLabel: 
         kubernetes.io/hostname: docker-desktop
```
