### ISSUE TITLE
Add redactor that supports string substitution

### ISSUE THREAD

**Issue by manderson23** [replicatedhq/troubleshoot#1616]
**Describe the rationale for the suggested feature.**

Add a redactor that supports string substitution. This could be useful where we want to anonymize but not hide data.

For example, I'd like to anonymize the hostnames of customer servers but would still like the traceability of consistent hostnames. A redactor that supports string substitution would allow replacing `customer.host.com` with `a.b.com`. 

**Describe the feature**

Add a new `substitute` redactor option with a configuration like

```yaml
redactors:
  - name: substitute hostnames
    removals:
      substitute:
      - target: server1.customer.com
        replacement: a.c.com
      - target: server2.customer.com
        replacement: b.c.com
```

**Describe alternatives you've considered**

Regex might be possible but would be cumbersome and error prone to configure for every environment
