### ISSUE TITLE
Failing analysis results appear when running preflights

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1625]
**Bug Description**

When we run preflights using the CLI using a spec that defines a location to upload results (`uploadResultsTo`), we see failing analysis results appearing. This only appears when using `preflight` CLI

**Expected Behavior**

We shouldn't see result failures appear.

**Steps To Reproduce**

Watch https://asciinema.org/a/Bo9k5KxeAjXTKGkdLzDKYJGj7 recording

Spec from the recording
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.16.0"
              message: The application requires Kubernetes 1.16.0 or later
              uri: https://kubernetes.io
          - warn:
              when: "< 1.17.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.17.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
  uploadResultsTo: http://localhost:8800
```

**Additional Context**

Include the following information.
- Troubleshoot version: v0.103.0
