### ISSUE TITLE
Warn isn't working with regex analyzer

### ISSUE THREAD

**Issue by theJaxon** [replicatedhq/troubleshoot#1652]
**Bug Description**

I'm trying to use **Warn** as an outcome for regex analyzer but it doesn't work, it shows fail instead

**Expected Behavior**

Just like the examples here https://troubleshoot.sh/docs/analyze/ , i expected that warn is supported as an option.

**Steps To Reproduce**

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: test
spec:
  collectors:
    - clusterResources:
        exclude: true
    - clusterInfo:
        exclude: true
  hostCollectors:
    - run:
        collectorName: test
        command: "sh"
        args:
          - -c
          - |
            #!/bin/bash
            echo "testing"

  analyzers:
    - textAnalyze:
        checkName:  "test"
        fileName: host-collectors/run-host/test.txt
        regex: 'Check passed'
        outcomes:
          - pass:
              when: "true"
              message: "Check passed."
          - warn:
              when: "false"
              message: "There seems to be an issue with the test."
```

**Additional Context**

Include the following information.
- Replicated Troubleshoot 0.85.0
- MacOS
- Sequoia 15.0.1
