### ISSUE TITLE
Create a `sysctl` host analyzer

### ISSUE THREAD

**Issue by JGAntunes** [replicatedhq/troubleshoot#1675]
**Describe the rationale for the suggested feature.**

Related to - https://github.com/replicatedhq/troubleshoot/issues/1674.

The current `sysctl` analyzer is in cluster specifc:
- https://troubleshoot.sh/docs/analyze/sysctl/
- https://github.com/replicatedhq/troubleshoot/blob/f0b8de68aecb4eefb356672a54a09354df4b72f9/pkg/analyze/sysctl.go#L41-L44

In our view a `sysct`l collector for the host, before a cluster is actually running is pretty valuable. Particularly for a lot of the work currently being done in embedded cluster - (e.g. https://github.com/replicatedhq/embedded-cluster/pull/1449 as well as ongoing work for arp filter detection).

**Describe the feature**

The analyzer spec would basically be the same as the one we have right now for the in cluster one:

```yaml
(...)
  analyzers:
    - sysctl:
        checkName: IP forwarding enabled
        outcomes:
        - fail:
            when: "net.ipv4.ip_forward = 0"
            message: "IP forwarding is not enabled"
```

Seems like for the current analyzer we also support greater/lower than comparisons, so it probably makes sense to support that here too:
- https://github.com/replicatedhq/troubleshoot/blob/main/pkg/analyze/sysctl.go#L163-L246

**Describe alternatives you've considered**

See - https://github.com/replicatedhq/troubleshoot/issues/1674-  for a list of the alternatives considered
