### ISSUE TITLE
URI field that returns content that isn't a support bundle causes analysis to fail

### ISSUE THREAD

**Issue by crdant** [replicatedhq/troubleshoot#1694]
**Bug Description**

I specified I URL to a non-existent object in Google Cloud storage, which led to an XML file being returned explaining the error. The caused the bundle analysis to fail when running `kubectl support-bundle --load-cluster-specs`.

**Expected Behavior**

The analyzers and collectors from the spec that is stored in the cluster will be run rather than the non-existent spec from the XML file leading to misbehavior.

**Steps To Reproduce**

You may be to reproduce with fewer steps, but this will make it most like what I encountered.

1. Include a `uri` field in a spec that points to a non-existent Google Cloud Storage object
2. Confirm a `curl` of that object returns an XML indicating an error
3. Store that spec in cluster with at least one other spec in the same namespace
4. Run `kubectl support-bundle --load-cluster-specs`
5. Observe that the TUI does not come up
6. Extract `analysis.json` from the bundle and notice its content is `[]`

**Comment by hedge-sparrow** [comment]
@crdant I'm trying to reproduce this with the following secret-spec:

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: support-bundle
  name: example
stringData:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: my-application-name
    spec:
      uri: https://storage.googleapis.com/foo_test_asdf/asdfasdf
      collectors:
        - cluster-resources: {}
```

but troubleshoot built from `main` gives me:

```
> support-bundle --load-cluster-specs
Error: no collectors specified to run. Use --debug and/or -v=2 to see more information
```

which version of troubleshoot was this tested with?

**Comment by hedge-sparrow** [comment]
@crdant I'm trying to reproduce this, could you share the spec that you're using? 

in my experiments, troubleshoot behaves as I would expect: the spec with the URI in it fails to load, but does not block execution of collectors / analyzers in the other specs, 

testing with the below two specs:

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: support-bundle
  name: example-a
stringData:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: my-application-name
    spec:
      collectors: 
        - cluster-resources: {}
      analyzers:
        - clusterVersion:
            outcomes:
              - fail:
                  when: "< 1.16.0"
                  message: The application requires Kubernetes 1.16.0 or later
                  uri: https://kubernetes.io
              - warn:
                  when: "< 1.17.0"
                  message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.17.0 or later.
                  uri: https://kubernetes.io
              - pass:
                  message: Your cluster meets the recommended and required versions of Kubernetes.

```

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: support-bundle
  name: example-b
stringData:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: my-application-name
    spec:
      uri: https://storage.googleapis.com/foo_test_asdf/asdfasdf
      collectors: 
        - etcd:
            image: quay.io/coreos/etcd:latest
      analyzers:
        - nodeResources:
            checkName: Total CPU Cores in the cluster is 20 or greater
            outcomes:
              - fail:
                  when: "sum(cpuCapacity) < 20"
                  message: The cluster must contain at least 20 cores
              - pass:
                  message: There are at least 20 cores in the cluster
```

```
> support-bundle --load-cluster-specs

[TUI shows]

A support bundle was generated and saved at support-bundle-2024-11-25T13_04_28.tar.gz. Please send this file to your software vendor for support.
```

```
> tar -xOf support-bundle-2024-11-25T13_04_28.tar.gz support-bundle-2024-11-25T13_04_28/analysis.json
[
    {
        "name": "required.kubernetes.version",
        "labels": {
            "desiredPosition": "1",
            "iconKey": "kubernetes_cluster_version",
            "iconUri": "https://troubleshoot.sh/images/analyzer-icons/kubernetes.svg?w=16\u0026h=16"
        },
        "insight": {
            "name": "required.kubernetes.version",
            "labels": {
                "iconKey": "kubernetes_cluster_version",
                "iconUri": "https://troubleshoot.sh/images/analyzer-icons/kubernetes.svg?w=16\u0026h=16"
            },
            "primary": "Required Kubernetes Version",
            "detail": "Your cluster meets the recommended and required versions of Kubernetes.",
            "severity": "debug"
        },
        "severity": "debug",
        "analyzerSpec": ""
    }
]⏎
```
