### ISSUE TITLE
Feature: add support for last-mile redactors 

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#171]
When running support-bundle, the user should be able to pass a path to a YAML file that contains specific redactors that define data to redact. Because this file is local, it can contain verify specific  patterns and values to redact.

An example spec could be:
```
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Redactor
metadata:
  name: sample
spec:
  patterns:
    - `(?i)(\\\"name\\\":\\\"[^\"]*JWT_?TOKEN\\\",\\\"value\\\":\\\")(?P<mask>[^\"]*)(\\\")`
  values:
    - my-secret-value
    - a-password
    - a-api-token
```

The end user would run this with:

```
kubectl support-bundle ./path-to-collectors.yaml --redactors ./path-to-redactors.yaml`
```

**Comment by laverya** [comment]
I broadly agree, with a pair of changes - 

first, IMO 'patterns' should be able to apply to subsets of files, leading to a file syntax like this:
```
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Redactor
metadata:
  name: sample
spec:
  patterns:
    - files:
       - '.*'
      replace:
       - `(?i)(\\\"name\\\":\\\"[^\"]*JWT_?TOKEN\\\",\\\"value\\\":\\\")(?P<mask>[^\"]*)(\\\")`
    - files:
       - `custom-collectors/.*`
       - `logs/.*`
      replace:
       - `(?i)(\d+\.\d+\.\d+\.\d+:)(?P<mask>\d+)`
  values:
    - my-secret-value
    - a-password
    - a-api-token
```
which would run the JWT_TOKEN redactor on all files, but the port filter on only files within `custom-collectors` or `logs`.

Second, if a 
```
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Redactor
```
file is present within the collectors, it should be applied - and if multiple redactors are supplied they should be merged.

**Comment by marccampbell** [comment]
I'd recommend that we introduce move each redactor into a type:

```
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Redactor
metadata:
  name: sample
spec:
  - name: remove api token
    files: "*"
    values: 
      - "a-api-token"
     -  "something else"
  - name: mask ip v4 in specific logs
    files:
      - "custom-collectors/*"
      - "logs/*"
    regex:
      - `(?i)(\\\"name\\\":\\\"[^\"]*JWT_?TOKEN\\\",\\\"value\\\":\\\")(?P<mask>[^\"]*)(\\\")`

```
