### ISSUE TITLE
Unable to check for deployment version using label

### ISSUE THREAD

**Issue by GauJosh** [replicatedhq/troubleshoot#1725]
**Bug Description**

I am trying to find istio version that is installed in my cluster but unable to do so.

**Expected Behavior**

Support bundle check should provide right output.

**Steps To Reproduce**

Here is my manifest:
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: supportbundle-test
spec:
  collectors:
 - cluster-resources:
      namespaces:
      - istio-system
  analyzers:
    - clusterResource:
        checkName: Istio-version
        kind: deployments
        namespace: istio-system
        name: istiod
        yamlPath: 'metadata.labels."operator.istio.io/version"'
        regex: "1.24.0"
        outcomes:
          - pass:
              when: ">= 1.24.0"
              message: "Your cluster meets the recommended and required istio version."
          - fail:
              when: "< 1.24.0"
              message: "The application requires at least istio 1.24.0"
```

I see the istio manifest is getting generated inside tar file. (support-bundle-2025-01-23T14_45_29/cluster-resources/deployments/istio-system.json)
Result I get is:

x Istio-version  resource does not exist

**Additional Context**

Include the following information.
- Troubleshoot version: 0.115.1
