### ISSUE TITLE
Copy collector does not copy folders

### ISSUE THREAD

**Issue by jdewinne** [replicatedhq/troubleshoot#1748]
**Bug Description**
When using the `copy` collector, it doesn't copy folders
Example:
Create a k8s cluster (for example using CMX with `replicated cluster create --distribution k3s`) and deploy netshoot in the default namespace. Make sure the label for app is specified.
Exec into the netshoot container and create the folder `/tmp/test` and also some subfolders and files.
Execute the following spec using `kubectl support-bundle`
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
  #Copies htdocs folder
    - copy:
        selector:
          - app=netshoot
        namespace: default
        containerPath: /tmp/test
```

**Expected Behavior**

The resulting support bundle should contain the corresponding files/folders.

**Steps To Reproduce**
See description

**Additional Context**

Include the following information.
- Troubleshoot version: 0.117.0
- k8s: k3s
