### ISSUE TITLE
Postgres analyzer version comparison fails for PostgreSQL 11

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/troubleshoot#191]
After fixing #187, trying to use 
```
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: preflight
spec:
  collectors:
  - postgres:
      uri: postgres://postgres:5432/cd4pe
  analyzers:
  - postgres:
      checkName: Must be postgres 9.6 or later
      outcomes:
        - fail:
            when: "connected == false"
            message: Cannot connect to postgres
        - fail:
            when: "version < 9.6.0"
            message: The postgres server must be at least version 9.6
        - pass:
            message: The postgres connection checks out
```
results in
> failed to compare postgres database conditional: failed to parse actual psotgres version: Invalid character(s) found in major number "PostgreSQL 11"

Note that there's also a typo in the error message.
