### ISSUE TITLE
Allocatable preflight checks are not flexible enough to use

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/troubleshoot#210]
The allocatable preflight checks seem useful to make sure that the cluster has enough resources we won't run into taints while installing the new application. However that only applies on new installs; on upgrade they may fail but it won't matter because the upgrade is just replacing existing resources.

**Comment by matias-manavella-nimble** [comment]
Hi @MikaelSmith,  what if you could specify a matchlabel selector for the installed deployment, so the analyzer checks first if a certain deployment already exists? If it's not deployed then runs the check of allocatable resources, and if it is already deployed pass.
Would that solve the issue?

**Comment by MikaelSmith** [comment]
That seems like it could work.

To some extent resources are still needed to perform the upgrade: need to spin up a new replica before terminating the previous one. It seems like I could use that conditional and have two checks: one for enough space to perform upgrades, the other only for new installs.

**Comment by matias-manavella-nimble** [comment]
Thats sounds right. Im thinking something like this, using the keywords `onInstall` and `onUpgrade` together with the application.matchLabel field. The analyzer checks if the deployment with the specified label exists (e.g: app=myapp) and acts in consequence. @markpundsack @divolgin what are your thoughts about this?

```YAML
- nodeResources:
        checkName: Check resources to install/upgrade the app.
        application:
          matchLabel:
            - app=myapp
        onInstall:
          filters:
            allocatableMemory: 16Gi
            cpuAllocatable: "6"
            selector:
                matchLabels: 
                kubernetes.io/role=app-primary-replica
          outcomes:
            - fail:
                when: "count() < 1"
                message: Must have 1 node with 16 GB (available) memory and 6 cores (on a single node) to install the application.
            - pass:
                message: This cluster has a node with enough memory and cpu to install the application. 
        onUpgrade:
          filters:
            allocatableMemory: 8Gi
            cpuAllocatable: "3"
          outcomes:
            - fail:
                when: "count() < 1"
                message: Must have 1 node with 8 GB (available) memory and 3 cores (on a single node) to Upgrade the app.
            - pass:
                message: This cluster has a node with enough memory and cpu capacity to upgrade your app.
```
