### ISSUE TITLE
Support passing an imagePullSecret in a run collector

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#247]
A run collector can only use public images today. It would be useful if the run collector schema supported an optional imagePullSecret to be added to the podSpec when creating. 

Additionally, it would be useful if the run collector could include the secret data (useful to templated and generated credentials). In this case, the run collector in troubleshoot would have to dynamically create the secret in the namespace (giving it a random name), and then using that generated secret name as the imagePullSecret in the podSpec. The secret should be deleted when completed.

**Comment by matias-manavella-nimble** [comment]
@marccampbell Hi Marc, I'm about to start working on this. I am thinking of defining a new set of specs for the run collector as follows:

A) If pod is going to use an existing secret: 
```YAML
- run:
        imagePullSecret:
            name: secrets_name
        collectorName: "run-ping"
        ...
```
B) If instead we want to create the secret (I used the example form: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/):
```YAML
- run:
        imagePullSecret:
            name: <random_if_not_specified>
            data: 
               .dockerconfigjson: UmVhbGx5IHJlYWxseSByZWVlZWVlZ...
            type: kubernetes.io/dockerconfigjson
        collectorName: "run-ping"
        ...
```
