### ISSUE TITLE
Secret collector always has empty key in result

### ISSUE THREAD

**Issue by areed** [replicatedhq/troubleshoot#258]
Running the following Secret collector returns the json result below with key an empty string.

```yaml
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: sample
spec:
  collectors:
    - secret:
        namespace: default
        name: my-secret
        key: password
        includeValue: true
```

```json
{
  "namespace": "default",
  "name": "my-secret",
  "key": "",
  "secretExists": true,
  "keyExists": true,
  "value": "mypass"
}
```
