### ISSUE TITLE
Support semver comparisons

### ISSUE THREAD

**Issue by areed** [replicatedhq/troubleshoot#275]
It should be possible to analyze a semver doing something like the below. Currently it's only possible to compare to integers in a textAnalyze when.

```
    - textAnalyze:
        checkName: Kotsadm version greater than or equal to 1.19.0
        filename: static/kots-version.txt
        regexGroups: '(?P<Version>\d+\.\d+.\d+)'
        outcomes:
          - fail:
              when: 'Version < 1.19.0'
              message: Your Kotsadm version does not meet required minimum version.
          - pass:
              message: Your Kotsadm version meets required minimum version.
  collectors:
    - data:
       name: static/kots-version.txt
       data: '{{repl KurlString "Kotsadm.Version"}}'
```
