### ISSUE TITLE
Postgres/Mysql/Redis analyzers should support a valueFrom for URI

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#300]
Currently, the only way to pass the URI to one of the database analyzers is to hard code it and write it into a spec. Often this is handled via templating to make it portable.

The uri field should support referencing an existing secret also, much like env vars do. Ideally, we can just reuse existing K8s objects and make it a struct, like:

```
uri:
  value: <>
  valueFrom:
    secretKeyRef:
     ...
```

**Comment by xavpaice** [comment]
@marccampbell is this issue still current?  Could use a bit more detail.

**Comment by xavpaice** [comment]
Marking as a feature: the ability to use a secret to populate the database connection info for a database collector.

**Comment by dexhorthy** [comment]
Just hit this and filed https://github.com/slackernews/slackernews/issues/66 while working on https://github.com/slackernews/slackernews/pull/41

For reference, my values are

```yaml
postgres:
  # tells slackernews to use postgres as the
  # backing database instead of sqlite
  enabled: false
  # deploys a postgresql workload to the cluster
  deploy_postgres: false
  # the password to use with deploy_postgres
  password: ""
  # if deploy_postgres is false, provide a URI
  uri: ""

  # use a value in an existing secret instead of
  # .postgres.password OR .postgres.uri
  existingSecretName: ""
  # key in the secret that contains the password
  existingSecretPasswordKey: ""
  # key in the secret that contains the uri
  existingSecretUriKey: ""
  # service type if deploy_postgres is true
  service:
    type: ClusterIP
    nodePort:
      port:
```

and my `collectors:` block looks like

```yaml
        {{- if and .Values.postgres.enabled
                   (not .Values.postgres.deploy_postgres)
                   (or
                       .Values.postgres.uri
                       (and .Values.postgres.existingSecretName
                            .Values.postgres.existingSecretUriKey))
                   }}
        - postgres:
            collectorName: postgres
            uri: >-
              {{- if (and .Values.postgres.existingSecretName
                          .Values.postgres.existingSecretUriKey)
              }}
                {{/*
                  # todo: add support for existing secret
                  {{ get value of uri key in existing secret }}
                */}}
              {{- else }}
                {{ .Values.postgres.uri }}
              {{- end }}
        {{- end }}
```
