### ISSUE TITLE
Use `storedVersions` of a CRD instead of a version from `spec.versions`

### ISSUE THREAD

**Issue by takirala** [replicatedhq/troubleshoot#608]
**Bug Description**

I have a CRD in my cluster that has (only relevant parts are listed here) :
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
spec:
  versions:
  - name: v1beta1
    ...
  - name: v1beta2
    ...
status:
  ...
  storedVersions:
  - v1beta2
```

**Expected Behavior**

When i try to collect a `support-bundle` i expected to see `v1beta2` version of the CR resource in the support bundle.

**Steps To Reproduce**

I cannot link the CR as it is a proprietary resource but any CRD with 1+ number of versions in `spec` can be used to replicate this.

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem
