### ISSUE TITLE
Add logic to update a spec if the URI field is defined

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#694]
## Request

Design: #681 

When presented with a spec document that contains a URI, if that spec is one of the specs provided on the command line or initial call to Troubleshoot, attempt to collect a replacement spec from that URI.  If successful, replace the entire spec with the one downloaded.  If unsuccessful, log the error and use the spec provided.

The URI is provided based on changes in #682 :

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: default
spec:
  uri: https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default.yaml
  collectors:
```

Likely starting point for this is to alter `ParseSupportBundleFromDoc()`in `pkg/supportbundle/load.go`.

We will need to test if the resulting supportBundle has a uri, and if it does, use the `loadSpec()` function to load a replacement spec.

## In scope

* Replacing the first spec document in a yaml file/secret/URL provided on the CLI with a URL download result (oci://, http://, https://), if successful
* Optionally, this URI could direct to a file, since `loadSpec()` tests for that already

## Out of scope

* Loading specs where the URI points to a secret (that's a different code path).
* yaml files with multiple documents will only read the URI from the first document in the file
* Redactors are out of scope, just the content of `collectors`and `analyzers`will be replaced
* preflights are out of scope
* KOTs calls `troubleshootv1beta2.CollectSupportBundleFromURI()`and `troubleshootv1beta2.CollectSupportBundleFromSpec()`to trigger support bundle collection.  These calls are not expected to be affected by these changes.

## Definition of done

- [x] CLI can accept a yaml file that has a `uri`specified (as above), and will download a replacement spec from that URI.
- [x] If the download fails, Troubleshoot continues to run without error, logging the failure only.  The originally provided spec is used.
- [ ] Code changes have tests

Docs to be added in #711
