### ISSUE TITLE
using textAnalyze regexGroups on runPods collectors does not return a real result

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#698]
**Bug Description**

When `textAnalyze`'s `regexGroups` options are used to parse results from a `runPods` collector, the analyzer returns a blank result and no `Message` is printed.

Looks like this happens with both Preflight and SupportBundle type specs.

**Expected Behavior**

I expect to get a Pass/Fail message under all circumstances where the spec is valid, or a runtime error returned telling me if I have a malformed spec.

**Steps To Reproduce**

```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: ping
spec:
  collectors:
    - runPod:
        name: "run-ping"
        namespace: default
        podSpec:
          containers:
            - name: run-ping
              image: busybox:1
              command: ["sh"]
              args: ['-c', 'echo SMTP server is reachable , PASS , blah blah message']
              imagePullPolicy: IfNotPresent
  analyzers:
    - textAnalyze:
        checkName: "run-ping"
        fileName: run-ping/run-ping.log
        regexGroups: 'SMTP server is reachable , (?P<Result>.*?) , (?P<Message>.*$)'
        outcomes:
          - pass:
              when: "Result == PASS"
              message: Passed
          - fail:
              when: "Result == FAIL"
              message: 'Result: {{ .Result }}'
    - textAnalyze:
        checkName: "run-ping-pass"
        fileName: run-ping/run-ping.log
        regex: 'PASS'
        outcomes:
          - pass:
              when: "true"
              message: Passed
          - fail:
              when: "false"
              message: 'Result: {{ .Result }}'
```

```
~/.krew/bin/kubectl-preflight ./preflight.yaml --debug
```
results in

<img width="875" alt="Screen Shot 2022-09-01 at 14 52 57" src="https://user-images.githubusercontent.com/292598/188000650-cc3b9bc7-40ed-4c59-aab2-e4f9d88bd342.png">

```
cat ping-results-2022-09-01T14_52_59.txt
Ping Preflight Checks

Title: run-ping
Message:

------------
Check PASS
Title: run-ping-pass
Message: Passed

------------
```

**Additional Context**
```
~/.krew/bin/kubectl-support_bundle version
Replicated Troubleshoot 0.40.0
```
