### ISSUE TITLE
copyFromHost collector should follow symlinks

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#715]
## Problem to solve (Required)

Ok, so I think I've made a bit of progress. It seems that's the copyFromHost command doesn't work with a symlink. On all my Ubuntu servers/desktops, /etc/os-release is actually a symlink to /usr/lib/os-release - when I put hostPath: /usr/lib/os-release, it works

So, my question is, how do we allow it to work with a symlink? According to the os-release docs, this may or may not be a symlink. If I can't use a symlink, it looks like this might be problematic for our use-case

## Proposal
 

copyFromHost collector should follow symlinks

## Further details

```
collectors:
- copyFromHost:
    collectorName: os-release
    image: busybox:1
    name: os-release
    hostPath: /etc/os-release
```

```
$ ls -l /etc/os-release
lrwxrwxrwx 1 root root 21 Feb 17 00:44 /etc/os-release -> ../usr/lib/os-release
$ cat /etc/os-release | grep VER
VERSION="20.04.4 LTS (Focal Fossa)"
```

## Impact (importance/urgency) (Required)

* Replicated impact:
* Vendor impact:
* End-user impact:

cannot create an analyzer to require a specific os
