### ISSUE TITLE
Support Bundle progress UI gets mashed together with bundle name

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/troubleshoot#728]
**Bug Description**

Support Bundle progress UI gets mashed together with bundle name

<img width="767" alt="Screen Shot 2022-09-20 at 4 15 09 PM" src="https://user-images.githubusercontent.com/3730605/191365903-fc0888be-eeec-4b14-90a3-e1eafe3c6075.png">

**Expected Behavior**

Clear progress UI or drop a newline before printing the bundle path. Or even "bundle generated at $PATH".

**Steps To Reproduce**

```
cat <<EOF > support-bundle.yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: workshop
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources:
        namespaces:
        - default
EOF

kubectl support-bundle support-bundle.yaml
```
**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.

0.42.0

- Operating system

MacOs

- Operating system version
 12.2.1

- Other details that might be helpful in diagnosing the problem
single node GKE cluster
