### ISSUE TITLE
It's hard to build a succinct regex log analyzer if a crashing pod's previous pod logs are collected

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/troubleshoot#732]
**Describe the rationale for the suggested feature.**

When collecting a bundle for a crashing pod, a top use case for troubleshoot is to be able to analyze a pod's logs to search for errors that might explain the crashloop. But troubleshoot is great at collecting the `kubectl logs -p` output, the logs from the previous crash. Because of how file path globbing works.

For example, if we have these logs in the bundle

```
x support-bundle-2022-09-19T19_41_59/pod-logs/my-app-59b8d785c7-wrv5s-previous.log
x support-bundle-2022-09-19T19_41_59/pod-logs/my-app-59b8d785c7-wrv5s.log
```

and this analyzer:

```
    - textAnalyze:
        checkName: No Errors in Logs
        fileName: pod-logs/my-app-*.log
        regex: 'prevent-start'
        outcomes:
          - pass:
              when: "false"
              message: "No concerning logs found"
          - fail:
              when: "true"
              message: |
                There's an error in startup -- if you forgot to prevent preventing starting, try removing the 'com.example.myapp/prevent-start' annotation
```

we get two of the same analyzer insight: 

<img width="986" alt="Screen Shot 2022-09-21 at 7 53 59 PM" src="https://user-images.githubusercontent.com/3730605/191637045-dc858253-b73f-4e60-bfa5-3624588305d7.png">

<img width="986" alt="Screen Shot 2022-09-21 at 8 11 24 PM" src="https://user-images.githubusercontent.com/3730605/191637033-723bfb86-2a5a-4918-b1d8-be827d727c96.png">

**Describe the feature**

Ideally we analyze the previous logs if they're there, otherwise collect the current ones. Unless the pod has been `Running` for a long time (hours or days) and is no longer in a `CrashLoopBackOff` -- then we don't care about the previous logs and would rather analyze the running pod.

In the short term, it would be great to be able to use a proper regex in `fileName` so we could at least choose one log output or the other and avoid having two.
