### ISSUE TITLE
Deduplication for Cluster Resources Collector

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#753]
### Problem to solve
With the recently added feature to concatenate multiple specs together at runtime, we need to ensure that we are not unnecessarily running the `Cluster Resources` collectors more than it should be. We need to implement deduplication for this collector so that if it's specified more than once with the same options, that it only runs once. 

### User Impact
- Troubleshoot may take longer to run due to a redundant operation

### Potential solution
Deduplicate any instances of the `Cluster Resources` collector in the final concatenated spec before running.

Example A:

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - clusterResources: {}
    - clusterResources: {}
```
End result should be
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - clusterResources: {}
```

**We should default to collecting more not less**

Example B:
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - clusterResources: {}
    - clusterResources:
        namespaces:
        - myapp-namespace
```
End result should be
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - clusterResources: {}
```

**Given two unique collectors, use them both**

Example C:
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - clusterResources:
        namespaces:
        - some-namespace
    - clusterResources:
        namespaces:
        - myapp-namespace
```
End result should be
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - clusterResources:
        namespaces:
        - some-namespace
    - clusterResources:
        namespaces:
        - myapp-namespace
```

## Definition of done

- [x] Deduplication for the cluster resources collector is added in its `Merge` function
- [x] Unit tests
