### ISSUE TITLE
`<object>Status` analzyers should be able to print a custom `message:` if a resource is not found

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#765]
**Describe the rationale for the suggested feature.**

While writing https://github.com/replicatedhq/troubleshoot/issues/712 I realized that `deploymentStatus` won't let you print a custom message if a deployment is not found.

For example, if I want to make sure that a deployment exists in a cluster, `deploymentStatus` will fail as expected if the deployment is not found, but does not print a `message:` since the messages rely on being able to get a # of replicas.

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - deploymentStatus:
        name: no-spoon
        namespace: default
        outcomes:
          - fail:
              message: there is no spoon
          - pass:
              when: "> 1"
              message: there is a spoon

...
------------
Check FAIL
Title: no-spoon Status
Message: The deployment "no-spoon" was not found

------------
/home/ada/support-bundle-results.txt (END)

```

**Describe the feature**

It would be nice to provide instructions in the event that something is expected to be installed but isn't.  I think the `...Status` analyzers should be able to print a message in the special failure case that an object does not exist or is not found.
