### ISSUE TITLE
Host Certificate Analyzer incorrectly shows "no results"

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#795]
**Bug Description**

Certificate Host Analyzer returns "no results" despite having valid input in the corresponding file that was collected.

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: cluster-down
spec:
  hostCollectors:
    - certificate:
        collectorName: k8s-api-keypair
        certificatePath: /etc/kubernetes/pki/apiserver.crt
        keyPath: /etc/kubernetes/pki/apiserver.key
  hostAnalyzers:
    - certificate:
        collectorName: k8s-api-keypair
        outcomes:
          - fail:
              when: "key-pair-missing"
              message: Certificate key pair not found in /etc/kubernetes/pki/apiserver.*
          - fail:
              when: "key-pair-switched"
              message: Cert and key pair are switched
          - fail:
              when: "key-pair-encrypted"
              message: Private key is encrypted
          - fail:
              when: "key-pair-mismatch"
              message: Cert and key do not match
          - fail:
              when: "key-pair-invalid"
              message: Certificate key pair is invalid
          - pass:
              when: "key-pair-valid"
              message: Certificate key pair is valid
```

Collected contents:
```
key-pair-valid
```

Analyzer returns:

```
{
        "name": "certificate.key.pair",
        "labels": {
            "desiredPosition": "1",
            "iconKey": "",
            "iconUri": ""
        },
        "insight": {
            "name": "certificate.key.pair",
            "labels": {
                "iconKey": "",
                "iconUri": ""
            },
            "primary": "Certificate Key Pair",
            "detail": "no results",
            "severity": "warn"
        },
        "severity": "warn",
        "analyzerSpec": ""
    }
```

**Expected Behavior**

The analyzer should properly show results based on the contents

**Steps To Reproduce**

> kubectl support-bundle --interactive=false https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/host/cluster-down.yaml
