### ISSUE TITLE
Velero Collector and Analyzer

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#806]
**Describe the rationale for the suggested feature.**

[Velero](https://github.com/vmware-tanzu/velero) is a toolset that allows you to backup/restore Kubernetes resources and persistent volumes. There are Kubernetes clusters where both Troubleshoot and Velero are commonly used and often times there is a lack of information and analysis that happens on the state of Velero in those environments

**Describe the feature**

A Velero Collector and Analyzer can be added to Support Bundle and Preflight specs.

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: velero
spec:
  collectors:
    - velero: {}
  analyzers:
    - velero: {}
```

The Velero Collector can collect information such as:
* `kubectl logs deploy/velero -n <velero-namespace> -c velero`
* `kubectl get bsl -n <velero-namespace>`
* `kubectl get bsl -n <velero-namespace> -oyaml`
* `kubectl get resticrepositories -n <velero-namespace>`
* `kubectl get resticrepositories -n <velero-namespace> -oyaml`
* `velero get backups`
* ???

The Velero Analyzer can provide the following analysis:
* ???

**Additional context**
