### ISSUE TITLE
Expand time for log collector maxAge to include days.

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/troubleshoot#864]
**Describe the rationale for the suggested feature.**

Users are specifying support bundle collectors like:

```
   - logs:
        name: redis
        selector:
          - app=redis
        limits:
          maxAge: 30d
          maxLines: 10000
```

But `30d` isn’t a [valid duration](https://pkg.go.dev/time#Duration) and needs to be ‘720h’ instead.

## Proposal

Add Days as a valid suffix since it's a typical way people measure log rotation. We should consider if adding other values such as weeks is valuable if it's trivial to expand to more than just days.

## Further details
From https://pkg.go.dev/time#ParseDuration: 

> A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

## Other

We should be sure whatever is implemented is appropriately documented.
