### ISSUE TITLE
Multiple runPod specs with the same name overwrite each other's data

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#895]
**Bug Description**

If two or more collector specs include the `runPod` collector with the same `name`, the second one to run will overwrite the data from the first.

Although it's not possible right now, if two run at the same time, with the same pod name, there will be a collision.

**Expected Behavior**

Each collector has a unique data output.

Each `runPod` collector starts a pod with a unique name.

**Steps To Reproduce**

Include the following in a spec:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - runPod:
        name: "run-ping"
        namespace: default
        podSpec: 
          containers:
          - name: run-ping
            image: busybox:1
            command: ["ping"]
            args: ["-w", "5", "www.google.com"]
    - runPod:
        name: "run-ping"
        namespace: default
        podSpec: 
          containers:
          - name: run-ping
            image: busybox:1
            command: ["ping"]
            args: ["-w", "5", "www.reddit.com"]
```

There may be other collectors that have the same problem, we have merely identified this with `runPod` at this point in time.

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.

0.49.1
