### ISSUE TITLE
Kubectl preflight --format=yaml results in error that yaml is an unknown output format

### ISSUE THREAD

**Issue by z4ce** [replicatedhq/troubleshoot#905]
**Bug Description**

Running with `kubectl preflight --format=yaml --interactive=false ...`
results in
```
name: cluster-resources    status: running         completed: 0    total: 2
name: cluster-resources    status: completed       completed: 1    total: 2
name: cluster-info         status: running         completed: 1    total: 2
name: cluster-info         status: completed       completed: 2    total: 2
Error: unknown output format: "yaml"
```
**Expected Behavior**
Output should be:
```yaml
pass:
    - title: Required Kubernetes Version
       message: Your cluster meets the recommended and required versions of Kubernetes.
```

**Steps To Reproduce**
Run the preflight plugin with `--format=yaml` worth noting that `--format=json` does work.

**Additional Context**
```
kubectl preflight version
Replicated Preflight 0.49.1
```
MacOS Ventura
