### ISSUE TITLE
ConfigMap collector should be namespace optional

### ISSUE THREAD

**Issue by mnp** [replicatedhq/troubleshoot#907]
**Describe the rationale for the suggested feature.**

The ConfigMap collector spec requires namespace to be provided.  As a vendor, we try not to dictate our installation namespace, so we don't know that ahead of time. If we hardcode a namespace into the support-bundle.yaml, we will not collect that CM if the namespaces don't match.

Some other collectors are already namespace-optional, for example `logs`, which makes sense:

    [namespace (Optional)](https://troubleshoot.sh/docs/collect/logs/#namespace-optional)
    The namespace to search for the pod selector in. If this is not provided, it will default to the current namespace of the context.

**Describe the feature**

The ConfigMap collector should parallel the logs one here.

**Describe alternatives you've considered**

**Additional context**

**Comment by chris-sanders** [comment]
@xavpaice I've marked this one triaged and good first issue, while I haven't looked through the code this seems reasonable and I suspect it's not that big of an ask to implement. You might want to check me on that :)

**Comment by xavpaice** [comment]
Thanks for raising the issue!

Likely this was overlooked previously because the spec can be templated (when provided by KOTS) - so the namespace is known.  Seems like a reasonable addition and the description is clear enough for folks to work on already.

**Comment by adamancini** [comment]
```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example-collect-all-configmap-data
spec:
  collectors:
    - configMap:
        name: kotsadm-application-metadata
```

results in error in support bundle files only, not at the CLI (which happens if you omit name or selector property):

```
 ✔  moira  ~/go/src/github.com/replicatedhq/troubleshoot/support-bundle-2023-01-03T14_16_40/configmaps-errors   ada/configmap-collector v0.52.0 ● ? ⍟1  cat kotsadm-application-metadata.json 
[
  "an empty namespace may not be set when a resource name is provided"
]
```

**Comment by adamancini** [comment]
@mnp we talked about some implementation details on our team standup today and wanted to ask a few questions and share some thoughts; we might consider making `namespace` mandatory for getting configmaps by name, and suggesting using label selectors as a way to grab configmaps across any namespace.  I think this aligns closer to the way the Kubernetes API works, since we can't select resources by name across all namespaces, and I don't know if we can expect that every end-user is going to have their kubectl context configured - we also imagined this might be a hurdle if an end-user needs to set a context other than `default` before a support bundle can be collected successfully.  We also imagined that there might be confusion if multiple apps were installed, and multiple namespaces have configmaps with the same name.

I think the difference with the Logs collector is that we still require a label there, and we can search first by label across all namespaces for pods, and then we apply the name and namespace filters to reduce that set.

I am curious though, f you're figuring out what the namespace is at runtime in the collector, can you show me what your analyzers look like for analyzing the configmap output?  However we make the change, I want to make sure we don't break analyzers specs.

**Comment by mnp** [comment]
@adamancini thank you for asking.  First of all, don't worry about breaking us - we are not using the CM collector yet.

Yes we could absolutely use selectors to identify configmaps for collection.  Our log collector looks like that already and grabbing CM the same way would be cleaner, in fact, than by name.

```yaml
  collectors:
    - logs:
        collectorName: mycorp
        selector:
          - mycorp-troubleshoot-collect=true
        name: logs
```

So if I understand your question:
 - getting CM by label with no namespace would be good
 - in which case we wouldn't care about getting CM by name with a namespace (we don't do it now)
 - we don't already have a CM collector so whatever you decide won't hurt us backward compat wise.

thanks again.

**Comment by adamancini** [comment]
@mnp sure, thanks! I think for some of the analyzers, like `regex` off the top of my head, takes a file path for analysis, and I think it can take a file path pattern, so you can still get analyzers working with dynamic namespaces -

the way I expect this to look, is if you collect all your configmaps by label, you should end up with a tree that looks like `configmaps/<namespace>/<configmap-name>.json`, so I think you could still match analyzers on configmap name with a wildcard on the namespace.

**Comment by xavpaice** [comment]
Couple of questions from me on this one:

- is there something in the query itself that requires a namespace, and if so can that be just the current context of the client?
- if we're happy to select by label, can we (should we) make that for all namespaces or just a specified one?

**Comment by adamancini** [comment]
@xavpaice 

> ... can that be the current context of the client?

yeah the implementation would have to be a little bit different than what `logs` collector is doing right now, but I think it's possible, but I may have to think on this a little more to get it working

> ... by label, can we (should we) make that for all namespaces ...

I think we should search all namespaces if the namespace is omitted, but if the namespace & label are specified, it should limit the search to that namespace

**Comment by chris-sanders** [comment]
>I think we should search all namespaces if the namespace is omitted, but if the namespace & label are specified, it should limit the search to that namespace

@adamancini searching all namespaces is not how kubectl works though, shouldn't we match kubectl and use the same search it would if you don't specify? (Based on your kubeconfig)

We might think it's the better choice, but matching kubectl functionality so users can assume how something works is fairly powerful.

**Comment by adamancini** [comment]
Ah since we are moving towards making queries in troubleshoot more kubectl-like, we can use `""` to designate all namespaces, and otherwise filter the search to what is specified

**Comment by adamancini** [comment]
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example-collect-all-configmap-data
spec:
  collectors:
    - configMap:
        name: kube-root-ca.crt
        # expected in default namespace
    - configMap:
        name: cluster-info
        # missing namespace parameter
    - configMap:
        name: does-not-exist
    - configMap:
        selector:
          - app=kube-proxy
        # only selector set
    - configMap:
        name: coredns
        namespace: kube-system
```

```
tail *
==> cluster-info.json <==
[
  "an empty namespace may not be set when a resource name is provided"
]

==> does-not-exist.json <==
[
  "an empty namespace may not be set when a resource name is provided"
]

==> kube-root-ca.crt.json <==
[
  "an empty namespace may not be set when a resource name is provided"
]
```
