### ISSUE TITLE
Kubernetes Events Analyzer

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#911]
**Describe the rationale for the suggested feature.**

Often times there are key indicators of issues within Kubernetes events. These events surface issues as it relates to scheduling, lack of resources, readiness timeouts. We should have an Events analyzer where you can specify one or all namespaces, match for text and evaluate it in a Warn/Fail/Pass condition similar to `textAnalyze` - https://troubleshoot.sh/docs/analyze/regex/

**Describe the feature**
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: bundle
spec:
  collectors:
    - clusterResources: {}
  analyzers:
    - eventsAnalyze:
        checkName: "insufficient-cpu"
        namespace: my-app
        regex: '.*Insufficient cpu.*'
        outcomes:
          - pass:
              when: "false"
              message: "Sufficient CPU for all Pods in my-app namespace"
          - fail:
              when: "true"
              message: "Insufficient CPU for some Pods in my-app namespace"
```

**Describe alternatives you've considered**

**Additional context**
