### ISSUE TITLE
`supportbundle-spec` label and `support-bundle-spec` data key in a secret-wrapped support bundle is inconsistent

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#913]
**Bug Description**

```
apiVersion: v1
kind: Secret
metadata:
  name: flannel-troubleshoot-spec
  labels:
    troubleshoot.io/kind: supportbundle-spec
stringData:
  support-bundle-spec: |
```

having both of these right next to each other is jarring and I think a potential source of confusion, since we don't have validation on the contents of Secrets, and we are potentially doing automation based on this label.  let's at least try to be consistent.   

**Expected Behavior**

perhaps something like `troubleshoot.io/kind: support-bundle` or `troubleshoot.io/kind: support-bundle-kind` would be a little more consistent with the data key
