### ISSUE TITLE
Generic Collector Deduplication

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#915]
**Describe the rationale for the suggested feature.**
Although some collectors will have special logic for dedup/merge similar to the [Cluster Resources Collector](https://github.com/replicatedhq/troubleshoot/pull/832), most every collector spec will benefit from a basic dedup that checks to ensure that the same entry isn't added twice. This is critical as the recently added features to discover SupportBundle specs within Secrets/Configmaps in the cluster become more utilized.

**Describe the feature**
If the below spec is given as input twice, it should only run once.

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: bundle1
spec:
  collectors:
    - clusterInfo: {}
    - http:
        name: healthz
        get:
          url: http://api:3000/healthz
    - data:
        collectorName: my-password-dump
        name: data
        data: |
          my super secret password is abc123
          another redaction will go here
    - runPod:
        name: "run-ping"
        namespace: default
        podSpec: 
          containers:
          - name: run-ping
            image: busybox:1
            command: ["ping"]
            args: ["-w", "5", "www.google.com"]
```

This change should be made for both the Support Bundle and Preflight CLIs

`pkg/supportbundle`
As desired collectors are being added in [runCollectors](https://github.com/replicatedhq/troubleshoot/blob/main/pkg/supportbundle/collect.go#L88-L99) and [runHostCollectors](https://github.com/replicatedhq/troubleshoot/blob/main/pkg/supportbundle/collect.go#L28-L34) ensure the destination list doesn't have duplicates

`pkg/preflight`
Same as above in [CollectHost](https://github.com/replicatedhq/troubleshoot/blob/main/pkg/preflight/collect.go#L89-L95) and [Collect](https://github.com/replicatedhq/troubleshoot/blob/main/pkg/preflight/collect.go#L142-L153)

**Describe alternatives you've considered**

**Additional context**
