### ISSUE TITLE
Host collectors hang when kubectl is 'broken'

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#921]
**Bug Description**

When collecting a support-bundle with only hostcollectors, and when for some reason kubectl commands 'hang' due to cluster state or configuration errors, `support-bundle` hangs.

Every time `support-bundle` or `preflight` is run, it automatically adds the `clusterInfo` and `clusterResources` collectors regardless of whether they're in the original spec or not.

**Expected Behavior**

Failure to collect `clusterInfo` and/or `clusterResources` within a short timeout period should result in a log, and graceful failure allowing the remaining collectors to run.

**Steps To Reproduce**

1. Find a machine or cluster where the config for kubectl is such that kubectl commands hang (it is not enough to replace the kubectl with a `while true` type loop, as `support-bundle` creates it's own client).
2. run support-bundle with a spec that contains just one very simple hostCollector
3. the process will not complete

**Additional Context**

**Comment by DexterYan** [comment]
### The configuration to reproduce the issue
- example.yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example
spec:
  hostCollectors:
    - run:
        collectorName: "get-pod"
        command: "kubectl"
        args: ["get", "pod"]
    - run:
        collectorName: "ping-google"
        command: "ping"
        args: ["-c", "5", "google.com"]
 ```
- ~/.kube/config: make the `server: https://*.*.*.*:6444` to some ip which has not been able to contact
- kubectl error: `Unable to connect to the server: dial tcp *.*.*.*:6444: i/o timeout`
- ./bin/support-bundle example.yaml

### Shouldn't Happen:
Host collectors hang for a long time and timeout

**Comment by DexterYan** [comment]
### Summary

It is not possible to reproduce the current issue when we only have `hostCollectors`.

### code analysis

when run `kubectl support-bundle` with only `hostCollectors`, the collect `clusterInfo` and `clusterResources` will not be triggered.

Based on https://github.com/replicatedhq/troubleshoot/blob/ebeed772870218947db691914995246624b63960/pkg/supportbundle/supportbundle.go#L106 the `collect.EnsureClusterResourcesFirst(` function will be only added if 
```
spec:
  collectors:
  - *****
```

According to https://github.com/replicatedhq/troubleshoot/blob/ebeed772870218947db691914995246624b63960/pkg/supportbundle/supportbundle.go#L96
if the HostCollectors is not empty, it will run runHostCollectors and will not add any `clusterInfo` and `clusterResources`.

So, if you are using support bundle example like https://github.com/replicatedhq/troubleshoot-specs/blob/main/host/cluster-down.yaml, it will not trigger the host collectors hang.

You can simply to reproduce Host Collectors will not hang by running `kubectl support-bundle example.yaml `
- example.yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
   name: example
spec:
   hostCollectors:
   - blockDevices: {}
```
- Replicated Troubleshoot 0.51.0

**Comment by itsMarydan** [comment]
Hi, I could help provide some information to replicate this behavior. IF you try disabling your DNS resolver for your host nodes that would be helpful

**Comment by DexterYan** [comment]
Hi @itsMarydan, thank you for your information. Could you also share your `SupportBundle` example yaml file for me to reproduce. I could not reproduce this issue by adding hostCollectors even after disable my DNS resolver. Here is my example.yaml for support bundle with only hostCollectors, could you try it
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
   name: example
spec:
   hostCollectors:
   - blockDevices: {}
```
in you device to see if you still have this issue.
