### ISSUE TITLE
an API/function/spec that will let us execute `kubectl debug` ephemeral pods

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#982]
**Describe the rationale for the suggested feature.**

to build on the `exec` collector, perhaps, we should start to support ephemeral containers executed by `kubectl debug`

ephemeral containers can attach to existing pods, with an image of choice, to run commands and extract data, and can also be executed at the Node scope for the same

**Describe the feature**

existing spec

```
- exec:
        name: mysql-version
        selector:
          - app=mysql
        namespace: default
        command: ["mysql"]
        args: ["-V"]
        timeout: 5s
```

maybe we could support something like

```
- exec:
        name: mysql-version
        ephemeralPod:
            image: nicolaka/netshoot
            target: mysql
            attach: false
        selector:
          - app=mysql
        namespace: default
        command: ["mysql"]
        args: ["-V"]
        timeout: 5s
- exec:
        name: htop
        ephemeralPod:
            image: nicolaka/netshoot
            target: node/hostname
            attach: false
        command: ["htop"]
        timeout: 5s
```
