### ISSUE TITLE
Host Collector and Analyzer to check subnet availability

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#984]
**Describe the rationale for the suggested feature.**

Before container networking components for Kubernetes clusters are installed, it's often necessary to ensure that there is no overlap in subnets between the route table of the machine used for the install and the desired subnets to be used for the container runtime and the container networking interface. We should introduce a host collector and analyzer that allows you to determine if a given subnet is already in use by the host. 

**Describe the feature**
* A host collector that gathers information from the routing table, checks against the input of the collector and makes a decision if there is an available subnet in the user provided range
* A host analyzer that checks the result written to the file by the collector

```yaml
# This example would have the collector check the routing table and make a decision sending the result of `yes/no` to the file
apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: subnet-available
spec:
  collectors:
    # would output yes/no depending if there is a /22 available in 10.0.0.0/8
    - subnetAvailable:
         CIDRRangeAlloc: "10.0.0.0/8"
         desiredCIDR: "/22"
  analyzers:
    - subnetAvailable:
        outcomes:
          - fail:
              when: "no-subnet-available"
              message: failed to find available subnet
          - pass:
              when: "subnet-available"
              message: available /22 subnet found
```

**Describe alternatives you've considered**

**Additional context**

https://github.com/replicatedhq/kURL/blob/main/kurl_util/cmd/subnet/main.go

**Comment by CpuID** [comment]
Just thinking through the big picture view of this collector/analyzer, let's take the below scenario assuming the following input:

```
  collectors:
    # would output yes/no depending if there is a /22 available in 10.0.0.0/8
    - subnetAvailable:
         CIDRRangeAlloc: "10.0.0.0/8"
         desiredCIDR: "/22"
  analyzers:
    - subnetAvailable:
        outcomes:
          - fail:
              when: "no-subnet-available"
              message: failed to find available subnet
          - pass:
              when: "subnet-available"
              message: available /22 subnet found
```

- user goes to install a cluster using [kURL](https://kurl.sh/), and the host preflights kick off and confirm "there's at least 1 free /22 available in 10.0.0.0/8 for use by this node"
- kURL continues with the cluster node installation, and uses its own independent logic in https://github.com/replicatedhq/kURL/blob/main/kurl_util/cmd/subnet/main.go to decide "this node will use this nominated subnet for podCIDR"

It feels to me like there would be 2 different things potentially selecting a subnet...? And they may not necessarily pick the same subnet? Just thinking through the likelihood of race conditions here, is there a path to say "the host preflight chose this subnet, kURL use this subnet" when it gets further along, rather than the 2 different implementations?
